#!/usr/bin/env python3
"""Generate the branch-asymmetry probe.

BZF and BZMF are the only Block II instructions whose cost depends on what they
find. A taken branch asserts NISQ and RAD in its own final subinstruction and so
fetches the next instruction for itself — one MCT. A branch not taken has
nothing to fetch with and falls through to an STD2 — two. Nothing else in the
instruction set varies like this, and it is exactly the sort of thing an
instruction-level emulator gets wrong for years without noticing.

The trick that makes it measurable is aiming every branch at the word directly
after it. Taken or not, control ends up in the same place, so both cases share
one measurement window and differ only in the MCT count.

The probe also pins down what "zero" means to a machine with two of them. BZF
branches on zero, and in ones' complement +0 (000000) and -0 (177777) are
numerically equal but not bit-equal. Both must branch. The hardware needs the
dedicated TMZ pulse precisely because a naive test would miss one of them, so a
probe that only ever tested +0 would pass on a broken TMZ.
"""
from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from asm import Asm, SCRATCH_START  # noqa: E402

ROOT = Path(__file__).resolve().parent.parent.parent
OUT_BIN = ROOT / "tests/probes/branches.bin"
OUT_META = ROOT / "tests/probes/branches.meta"

SENTINEL_BASE = SCRATCH_START + 0o20  # 0120


def _branch(a, k, load, kind):
    """<load A> ; EXTEND ; B<kind> <the next word>."""
    load(a, k)
    a.extend()
    target = a.here() + 1
    if kind == "bzf":
        a.bzf(target)
    else:
        a.bzmf(target)


def ld_plus_zero(a, k):  a.ca(k["zero"])   # +0: 000000
def ld_minus_zero(a, k): a.cs(k["zero"])   # -0: 177777
def ld_plus_one(a, k):   a.ca(k["one"])
def ld_minus_one(a, k):  a.cs(k["one"])


# (name, expected instruction-block cost in MCTs, load, branch)
#
# Cost is the accumulator load (2) + EXTEND (1) + the branch itself:
# 1 MCT taken, 2 not taken.
MEASUREMENTS = [
    ("BZF_PLUS_ZERO",    4, ld_plus_zero,  "bzf"),   # taken
    ("BZF_MINUS_ZERO",   4, ld_minus_zero, "bzf"),   # taken — the other zero
    ("BZF_POSITIVE",     5, ld_plus_one,   "bzf"),   # not taken
    ("BZF_NEGATIVE",     5, ld_minus_one,  "bzf"),   # not taken
    ("BZMF_PLUS_ZERO",   4, ld_plus_zero,  "bzmf"),  # taken
    ("BZMF_MINUS_ZERO",  4, ld_minus_zero, "bzmf"),  # taken
    ("BZMF_NEGATIVE",    4, ld_minus_one,  "bzmf"),  # taken — zero *or minus*
    ("BZMF_POSITIVE",    5, ld_plus_one,   "bzmf"),  # not taken
]


def build():
    a = Asm()
    one = a.label("one")
    zero = a.label("zero")
    k = {"one": one, "zero": zero}

    sentinels = []
    for i, (name, expected, load, kind) in enumerate(MEASUREMENTS):
        sa = SENTINEL_BASE + 2 * i
        sb = SENTINEL_BASE + 2 * i + 1
        a.ca(one)
        a.ts(sa)
        _branch(a, k, load, kind)
        a.ca(one)
        a.ts(sb)
        sentinels.append((name, sa, sb, expected))

    park = a.label("park")
    a.tcf(park)

    one.addr = a.here();  a.word(1)
    zero.addr = a.here(); a.word(0)

    return a, sentinels


def main() -> int:
    a, sentinels = build()
    OUT_BIN.parent.mkdir(parents=True, exist_ok=True)
    a.write_rope(str(OUT_BIN))

    lines = [
        "# Generated by tools/probes/gen_branch_probe.py — do not edit.",
        "# Each window is <load A> + EXTEND + branch, plus the usual CA + TS",
        "# overhead of 4 MCTs. A taken branch costs 1 MCT, one not taken costs 2.",
        "flags --ignore-counters",
        "# name  open-sentinel  close-sentinel  expected-window-MCTs",
    ]
    for name, sa, sb, expected in sentinels:
        lines.append(f"measure {name} {sa:04o} {sb:04o} {expected + 4}")
    lines.append("# Taking a branch must be cheaper than not taking one.")
    lines.append("relation BZF_PLUS_ZERO BZF_POSITIVE b_longer_by_whole_mcts")
    lines.append("relation BZMF_NEGATIVE BZMF_POSITIVE b_longer_by_whole_mcts")
    OUT_META.write_text("\n".join(lines) + "\n")

    print(f"wrote {OUT_BIN.relative_to(ROOT)} and {OUT_META.relative_to(ROOT)}: "
          f"{len(sentinels)} measurements, {a.here() - 0o4000} words")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
