/* GENERATED by tools/gen_subinst_tables.py — do not edit by hand.
 *
 * The Block II control-pulse sequences: for every subinstruction, which
 * control pulses fire at which timing pulse T1-T12, under which branch
 * register condition.  Transcribed from AGC4 Memo #9
 * (docs/references/AgcPulsesAndSequences.txt) as corrected by the
 * control-pulse reference model in ext/agcplusplus; divergences between the
 * two are catalogued in tools/oracle/FINDINGS.md.
 *
 * BR conditions use the memo's own encoding: br = (BR1 << 1) | BR2, with
 * br_mask selecting which of the two bits the row cares about (the memo's
 * 'x' is a zero mask bit).
 */
#include "subinst.h"

static const agc_pulse_row ad0_rows[] = {
    {  2, 0x0, 0x0, { AGC_P_RSC, AGC_P_WG } },  /* T2 xx */
    {  7, 0x0, 0x0, { AGC_P_RG, AGC_P_WB } },  /* T7 xx */
    {  8, 0x0, 0x0, { AGC_P_RZ, AGC_P_WS, AGC_P_ST2 } },  /* T8 xx */
    {  9, 0x0, 0x0, { AGC_P_RB, AGC_P_WG } },  /* T9 xx */
    { 10, 0x0, 0x0, { AGC_P_RB, AGC_P_WY, AGC_P_A2X } },  /* T10 xx */
    { 11, 0x0, 0x0, { AGC_P_RU, AGC_P_WA } },  /* T11 xx */
};

static const agc_pulse_row ads0_rows[] = {
    {  1, 0x0, 0x0, { AGC_P_RL10BB, AGC_P_WS } },  /* T1 xx */
    {  2, 0x0, 0x0, { AGC_P_RSC, AGC_P_WG } },  /* T2 xx */
    {  5, 0x0, 0x0, { AGC_P_RG, AGC_P_WY, AGC_P_A2X } },  /* T5 xx */
    {  6, 0x0, 0x0, { AGC_P_RU, AGC_P_WSC, AGC_P_WG, AGC_P_TOV } },  /* T6 xx */
    {  7, 0x3, 0x0, { AGC_P_WA } },  /* T7 00 */
    {  7, 0x3, 0x1, { AGC_P_RB1, AGC_P_WA } },  /* T7 01 */
    {  7, 0x3, 0x2, { AGC_P_R1C, AGC_P_WA } },  /* T7 10 */
    {  7, 0x3, 0x3, { AGC_P_WA } },  /* T7 11 */
    {  8, 0x0, 0x0, { AGC_P_RZ, AGC_P_WS, AGC_P_ST2 } },  /* T8 xx */
    {  9, 0x0, 0x0, { AGC_P_RC, AGC_P_TMZ } },  /* T9 xx */
    { 11, 0x0, 0x0, { AGC_P_RU, AGC_P_WA } },  /* T11 xx */
};

static const agc_pulse_row aug0_rows[] = {
    {  1, 0x0, 0x0, { AGC_P_RL10BB, AGC_P_WS } },  /* T1 xx */
    {  2, 0x0, 0x0, { AGC_P_RSC, AGC_P_WG } },  /* T2 xx */
    {  5, 0x0, 0x0, { AGC_P_RG, AGC_P_WY, AGC_P_TSGN, AGC_P_TMZ, AGC_P_TPZG } },  /* T5 xx */
    {  6, 0x2, 0x0, { AGC_P_PONEX } },  /* T6 0x */
    {  6, 0x2, 0x2, { AGC_P_MONEX } },  /* T6 1x */
    {  7, 0x0, 0x0, { AGC_P_RU, AGC_P_WSC, AGC_P_WG, AGC_P_WOVR } },  /* T7 xx */
    {  8, 0x0, 0x0, { AGC_P_RZ, AGC_P_WS, AGC_P_ST2 } },  /* T8 xx */
};

static const agc_pulse_row bzf0_rows[] = {
    {  1, 0x0, 0x0, { AGC_P_RA, AGC_P_WG, AGC_P_TSGN, AGC_P_TMZ } },  /* T1 xx */
    {  2, 0x0, 0x0, { AGC_P_TPZG } },  /* T2 xx */
    {  3, 0x0, 0x0, { AGC_P_RSC, AGC_P_WG } },  /* T3 xx */
    {  5, 0x1, 0x1, { AGC_P_RB, AGC_P_WY12, AGC_P_CI } },  /* T5 x1 */
    {  6, 0x1, 0x1, { AGC_P_RU, AGC_P_WZ } },  /* T6 x1 */
    {  8, 0x1, 0x0, { AGC_P_RZ, AGC_P_WS, AGC_P_ST2 } },  /* T8 x0 */
    {  8, 0x1, 0x1, { AGC_P_RAD, AGC_P_WB, AGC_P_WS, AGC_P_NISQ } },  /* T8 x1 */
};

static const agc_pulse_row bzmf0_rows[] = {
    {  1, 0x0, 0x0, { AGC_P_RA, AGC_P_WG, AGC_P_TSGN, AGC_P_TMZ } },  /* T1 xx */
    {  2, 0x0, 0x0, { AGC_P_TPZG } },  /* T2 xx */
    {  3, 0x0, 0x0, { AGC_P_RSC, AGC_P_WG } },  /* T3 xx */
    {  5, 0x2, 0x2, { AGC_P_RB, AGC_P_WY12, AGC_P_CI } },  /* T5 1x */
    {  5, 0x3, 0x1, { AGC_P_RB, AGC_P_WY12, AGC_P_CI } },  /* T5 01 */
    {  6, 0x2, 0x2, { AGC_P_RU, AGC_P_WZ } },  /* T6 1x */
    {  6, 0x3, 0x1, { AGC_P_RU, AGC_P_WZ } },  /* T6 01 */
    {  8, 0x2, 0x2, { AGC_P_RAD, AGC_P_WB, AGC_P_WS, AGC_P_NISQ } },  /* T8 1x */
    {  8, 0x3, 0x0, { AGC_P_RZ, AGC_P_WS, AGC_P_ST2 } },  /* T8 00 */
    {  8, 0x3, 0x1, { AGC_P_RAD, AGC_P_WB, AGC_P_WS, AGC_P_NISQ } },  /* T8 01 */
};

static const agc_pulse_row ca0_rows[] = {
    {  2, 0x0, 0x0, { AGC_P_RSC, AGC_P_WG } },  /* T2 xx */
    {  7, 0x0, 0x0, { AGC_P_RG, AGC_P_WB } },  /* T7 xx */
    {  8, 0x0, 0x0, { AGC_P_RZ, AGC_P_WS, AGC_P_ST2 } },  /* T8 xx */
    {  9, 0x0, 0x0, { AGC_P_RB, AGC_P_WG } },  /* T9 xx */
    { 10, 0x0, 0x0, { AGC_P_RB, AGC_P_WA } },  /* T10 xx */
};

static const agc_pulse_row ccs0_rows[] = {
    {  1, 0x0, 0x0, { AGC_P_RL10BB, AGC_P_WS } },  /* T1 xx */
    {  2, 0x0, 0x0, { AGC_P_RSC, AGC_P_WG } },  /* T2 xx */
    {  5, 0x0, 0x0, { AGC_P_RG, AGC_P_WB, AGC_P_TSGN, AGC_P_TMZ, AGC_P_TPZG } },  /* T5 xx */
    {  7, 0x3, 0x0, { AGC_P_RZ, AGC_P_WY12 } },  /* T7 00 */
    {  7, 0x3, 0x1, { AGC_P_RZ, AGC_P_WY12, AGC_P_PONEX } },  /* T7 01 */
    {  7, 0x3, 0x2, { AGC_P_RZ, AGC_P_WY12, AGC_P_PTWOX } },  /* T7 10 */
    {  7, 0x3, 0x3, { AGC_P_RZ, AGC_P_WY12, AGC_P_PONEX, AGC_P_PTWOX } },  /* T7 11 */
    {  8, 0x0, 0x0, { AGC_P_RU, AGC_P_WZ, AGC_P_WS } },  /* T8 xx */
    {  9, 0x0, 0x0, { AGC_P_RB, AGC_P_WG } },  /* T9 xx */
    { 10, 0x1, 0x1, { AGC_P_WY, AGC_P_ST2 } },  /* T10 x1 */
    { 10, 0x3, 0x0, { AGC_P_RB, AGC_P_WY, AGC_P_MONEX, AGC_P_CI, AGC_P_ST2 } },  /* T10 00 */
    { 10, 0x3, 0x2, { AGC_P_RC, AGC_P_WY, AGC_P_MONEX, AGC_P_CI, AGC_P_ST2 } },  /* T10 10 */
    { 11, 0x0, 0x0, { AGC_P_RU, AGC_P_WA } },  /* T11 xx */
};

static const agc_pulse_row cs0_rows[] = {
    {  2, 0x0, 0x0, { AGC_P_RSC, AGC_P_WG } },  /* T2 xx */
    {  7, 0x0, 0x0, { AGC_P_RG, AGC_P_WB } },  /* T7 xx */
    {  8, 0x0, 0x0, { AGC_P_RZ, AGC_P_WS, AGC_P_ST2 } },  /* T8 xx */
    {  9, 0x0, 0x0, { AGC_P_RB, AGC_P_WG } },  /* T9 xx */
    { 10, 0x0, 0x0, { AGC_P_RC, AGC_P_WA } },  /* T10 xx */
};

static const agc_pulse_row das0_rows[] = {
    {  1, 0x0, 0x0, { AGC_P_RL10BB, AGC_P_WS, AGC_P_WY12, AGC_P_MONEX, AGC_P_CI } },  /* T1 xx */
    {  2, 0x0, 0x0, { AGC_P_RSC, AGC_P_WG } },  /* T2 xx */
    {  3, 0x0, 0x0, { AGC_P_RA, AGC_P_WB } },  /* T3 xx */
    {  4, 0x0, 0x0, { AGC_P_RL, AGC_P_WA } },  /* T4 xx */
    {  5, 0x0, 0x0, { AGC_P_RU, AGC_P_WL } },  /* T5 xx */
    {  6, 0x0, 0x0, { AGC_P_RG, AGC_P_WY, AGC_P_A2X } },  /* T6 xx */
    {  7, 0x0, 0x0, { AGC_P_RB, AGC_P_WA } },  /* T7 xx */
    {  8, 0x0, 0x0, { AGC_P_RL, AGC_P_WB } },  /* T8 xx */
    {  9, 0x0, 0x0, { AGC_P_RU, AGC_P_WSC, AGC_P_WG, AGC_P_TOV } },  /* T9 xx */
    { 10, 0x3, 0x0, { AGC_P_RA, AGC_P_WY, AGC_P_ST1 } },  /* T10 00 */
    { 10, 0x3, 0x1, { AGC_P_RA, AGC_P_WY, AGC_P_ST1, AGC_P_PONEX } },  /* T10 01 */
    { 10, 0x3, 0x2, { AGC_P_RA, AGC_P_WY, AGC_P_ST1, AGC_P_MONEX } },  /* T10 10 */
    { 10, 0x3, 0x3, { AGC_P_RA, AGC_P_WY, AGC_P_ST1 } },  /* T10 11 */
};

static const agc_pulse_row das1_rows[] = {
    {  1, 0x0, 0x0, { AGC_P_RL10BB, AGC_P_WS } },  /* T1 xx */
    {  2, 0x0, 0x0, { AGC_P_RSC, AGC_P_WG } },  /* T2 xx */
    {  3, 0x0, 0x0, { AGC_P_RU, AGC_P_WA } },  /* T3 xx */
    {  5, 0x0, 0x0, { AGC_P_RG, AGC_P_WY, AGC_P_A2X } },  /* T5 xx */
    {  6, 0x0, 0x0, { AGC_P_RU, AGC_P_WG, AGC_P_WSC, AGC_P_TOV } },  /* T6 xx */
    {  7, 0x3, 0x0, { AGC_P_WA } },  /* T7 00 */
    {  7, 0x3, 0x1, { AGC_P_RB1, AGC_P_WA } },  /* T7 01 */
    {  7, 0x3, 0x2, { AGC_P_R1C, AGC_P_WA } },  /* T7 10 */
    {  7, 0x3, 0x3, { AGC_P_WA } },  /* T7 11 */
    {  8, 0x0, 0x0, { AGC_P_RZ, AGC_P_WS, AGC_P_ST2 } },  /* T8 xx */
    {  9, 0x0, 0x0, { AGC_P_RC, AGC_P_TMZ } },  /* T9 xx */
    { 10, 0x1, 0x0, { AGC_P_WL } },  /* T10 x0 */
    { 11, 0x1, 0x1, { AGC_P_RU, AGC_P_WA } },  /* T11 x1 */
};

static const agc_pulse_row dca0_rows[] = {
    {  1, 0x0, 0x0, { AGC_P_RB, AGC_P_WY12, AGC_P_MONEX, AGC_P_CI } },  /* T1 xx */
    {  2, 0x0, 0x0, { AGC_P_RSC, AGC_P_WG } },  /* T2 xx */
    {  7, 0x0, 0x0, { AGC_P_RG, AGC_P_WB } },  /* T7 xx */
    {  8, 0x0, 0x0, { AGC_P_RU, AGC_P_WS } },  /* T8 xx */
    {  9, 0x0, 0x0, { AGC_P_RB, AGC_P_WG } },  /* T9 xx */
    { 10, 0x0, 0x0, { AGC_P_RB, AGC_P_WL, AGC_P_ST1 } },  /* T10 xx */
};

static const agc_pulse_row dca1_rows[] = {
    {  2, 0x0, 0x0, { AGC_P_RSC, AGC_P_WG } },  /* T2 xx */
    {  7, 0x0, 0x0, { AGC_P_RG, AGC_P_WB } },  /* T7 xx */
    {  8, 0x0, 0x0, { AGC_P_RZ, AGC_P_WS, AGC_P_ST2 } },  /* T8 xx */
    {  9, 0x0, 0x0, { AGC_P_RB, AGC_P_WG } },  /* T9 xx */
    { 10, 0x0, 0x0, { AGC_P_RB, AGC_P_WA } },  /* T10 xx */
};

static const agc_pulse_row dcs0_rows[] = {
    {  1, 0x0, 0x0, { AGC_P_RB, AGC_P_WY12, AGC_P_MONEX, AGC_P_CI } },  /* T1 xx */
    {  2, 0x0, 0x0, { AGC_P_RSC, AGC_P_WG } },  /* T2 xx */
    {  7, 0x0, 0x0, { AGC_P_RG, AGC_P_WB } },  /* T7 xx */
    {  8, 0x0, 0x0, { AGC_P_RU, AGC_P_WS } },  /* T8 xx */
    {  9, 0x0, 0x0, { AGC_P_RB, AGC_P_WG } },  /* T9 xx */
    { 10, 0x0, 0x0, { AGC_P_RC, AGC_P_WL, AGC_P_ST1 } },  /* T10 xx */
};

static const agc_pulse_row dcs1_rows[] = {
    {  2, 0x0, 0x0, { AGC_P_RSC, AGC_P_WG } },  /* T2 xx */
    {  7, 0x0, 0x0, { AGC_P_RG, AGC_P_WB } },  /* T7 xx */
    {  8, 0x0, 0x0, { AGC_P_RZ, AGC_P_WS, AGC_P_ST2 } },  /* T8 xx */
    {  9, 0x0, 0x0, { AGC_P_RB, AGC_P_WG } },  /* T9 xx */
    { 10, 0x0, 0x0, { AGC_P_RC, AGC_P_WA } },  /* T10 xx */
};

static const agc_pulse_row dim0_rows[] = {
    {  1, 0x0, 0x0, { AGC_P_RL10BB, AGC_P_WS } },  /* T1 xx */
    {  2, 0x0, 0x0, { AGC_P_RSC, AGC_P_WG } },  /* T2 xx */
    {  5, 0x0, 0x0, { AGC_P_RG, AGC_P_WY, AGC_P_TSGN, AGC_P_TMZ, AGC_P_TPZG } },  /* T5 xx */
    {  6, 0x3, 0x0, { AGC_P_MONEX } },  /* T6 00 */
    {  6, 0x3, 0x2, { AGC_P_PONEX } },  /* T6 10 */
    {  7, 0x0, 0x0, { AGC_P_RU, AGC_P_WSC, AGC_P_WG, AGC_P_WOVR } },  /* T7 xx */
    {  8, 0x0, 0x0, { AGC_P_RZ, AGC_P_WS, AGC_P_ST2 } },  /* T8 xx */
};

static const agc_pulse_row dinc_rows[] = {
    {  1, 0x0, 0x0, { AGC_P_RSCT, AGC_P_WS } },  /* T1 xx */
    {  2, 0x0, 0x0, { AGC_P_RSC, AGC_P_WG } },  /* T2 xx */
    {  5, 0x0, 0x0, { AGC_P_RG, AGC_P_WY, AGC_P_TSGN, AGC_P_TMZ, AGC_P_TPZG } },  /* T5 xx */
    {  6, 0x1, 0x1, { AGC_P_ZOUT } },  /* T6 x1 */
    {  6, 0x3, 0x0, { AGC_P_MONEX, AGC_P_POUT } },  /* T6 00 */
    {  6, 0x3, 0x2, { AGC_P_PONEX, AGC_P_MOUT } },  /* T6 10 */
    {  7, 0x0, 0x0, { AGC_P_RU, AGC_P_WSC, AGC_P_WG, AGC_P_WOVR } },  /* T7 xx */
    {  8, 0x0, 0x0, { AGC_P_RB, AGC_P_WS } },  /* T8 xx */
};

static const agc_pulse_row dv0_rows[] = {
    {  1, 0x0, 0x0, { AGC_P_P1XP10, AGC_P_RA, AGC_P_WB, AGC_P_TSGN, AGC_P_TMZ } },  /* T1 xx */
    {  2, 0x2, 0x0, { AGC_P_RC, AGC_P_WA, AGC_P_TMZ, AGC_P_DVST } },  /* T2 0x */
    {  2, 0x2, 0x2, { AGC_P_DVST } },  /* T2 1x */
    {  3, 0x0, 0x0, { AGC_P_RU, AGC_P_WB, AGC_P_STAGE } },  /* T3 xx */
};

static const agc_pulse_row dv1_rows[] = {
    {  1, 0x0, 0x0, { AGC_P_L2GD, AGC_P_RB, AGC_P_PIFL, AGC_P_WYD, AGC_P_A2X } },  /* T1 xx */
    {  2, 0x0, 0x0, { AGC_P_RG, AGC_P_TSGU, AGC_P_CLXC, AGC_P_RB1F, AGC_P_WL, AGC_P_DVST } },  /* T2 xx */
    {  3, 0x0, 0x0, { AGC_P_RU, AGC_P_WB, AGC_P_STAGE } },  /* T3 xx */
    {  4, 0x1, 0x0, { AGC_P_RL, AGC_P_WB } },  /* T4 x0 */
    {  4, 0x1, 0x1, { AGC_P_RL, AGC_P_WB, AGC_P_TSGN } },  /* T4 x1 */
    {  5, 0x2, 0x0, { AGC_P_RB, AGC_P_WY, AGC_P_B15X } },  /* T5 0x */
    {  5, 0x2, 0x2, { AGC_P_RC, AGC_P_WY, AGC_P_B15X, AGC_P_Z16 } },  /* T5 1x */
    {  6, 0x0, 0x0, { AGC_P_RU, AGC_P_WL, AGC_P_TOV } },  /* T6 xx */
    {  7, 0x0, 0x0, { AGC_P_RG, AGC_P_RSC, AGC_P_WB, AGC_P_TSGN } },  /* T7 xx */
    {  8, 0x1, 0x0, { AGC_P_RA, AGC_P_WY, AGC_P_PONEX, AGC_P_P8XP5 } },  /* T8 x0 */
    {  8, 0x1, 0x1, { AGC_P_RA, AGC_P_WY, AGC_P_P8XP5 } },  /* T8 x1 */
    {  9, 0x2, 0x0, { AGC_P_RB, AGC_P_WA } },  /* T9 0x */
    {  9, 0x2, 0x2, { AGC_P_RC, AGC_P_WA, AGC_P_Z15 } },  /* T9 1x */
    { 10, 0x0, 0x0, { AGC_P_RU, AGC_P_WB } },  /* T10 xx */
    { 11, 0x0, 0x0, { AGC_P_RL, AGC_P_WYD } },  /* T11 xx */
    { 12, 0x0, 0x0, { AGC_P_RU, AGC_P_WL } },  /* T12 xx */
};

static const agc_pulse_row dv3_rows[] = {
    {  1, 0x0, 0x0, { AGC_P_L2GD, AGC_P_RB, AGC_P_PIFL, AGC_P_WYD, AGC_P_A2X } },  /* T1 xx */
    {  2, 0x0, 0x0, { AGC_P_RG, AGC_P_TSGU, AGC_P_CLXC, AGC_P_RB1F, AGC_P_WL, AGC_P_DVST } },  /* T2 xx */
    {  3, 0x0, 0x0, { AGC_P_RU, AGC_P_WB, AGC_P_STAGE } },  /* T3 xx */
    {  4, 0x0, 0x0, { AGC_P_L2GD, AGC_P_RB, AGC_P_PIFL, AGC_P_WYD, AGC_P_A2X } },  /* T4 xx */
    {  5, 0x0, 0x0, { AGC_P_RG, AGC_P_TSGU, AGC_P_CLXC, AGC_P_RB1F, AGC_P_WL } },  /* T5 xx */
    {  6, 0x0, 0x0, { AGC_P_RU, AGC_P_WB } },  /* T6 xx */
    {  7, 0x0, 0x0, { AGC_P_L2GD, AGC_P_RB, AGC_P_PIFL, AGC_P_WYD, AGC_P_A2X } },  /* T7 xx */
    {  8, 0x0, 0x0, { AGC_P_RG, AGC_P_TSGU, AGC_P_CLXC, AGC_P_RB1F, AGC_P_WL } },  /* T8 xx */
    {  9, 0x0, 0x0, { AGC_P_RU, AGC_P_WB } },  /* T9 xx */
    { 10, 0x0, 0x0, { AGC_P_L2GD, AGC_P_RB, AGC_P_PIFL, AGC_P_WYD, AGC_P_A2X } },  /* T10 xx */
    { 11, 0x0, 0x0, { AGC_P_RG, AGC_P_TSGU, AGC_P_CLXC, AGC_P_RB1F, AGC_P_WL } },  /* T11 xx */
    { 12, 0x0, 0x0, { AGC_P_RU, AGC_P_WB } },  /* T12 xx */
};

static const agc_pulse_row dv4_rows[] = {
    {  4, 0x0, 0x0, { AGC_P_L2GD, AGC_P_RB, AGC_P_PIFL, AGC_P_WYD, AGC_P_A2X } },  /* T4 xx */
    {  5, 0x0, 0x0, { AGC_P_RG, AGC_P_TSGU, AGC_P_CLXC, AGC_P_RB1F, AGC_P_WB, AGC_P_WA } },  /* T5 xx */
    {  6, 0x0, 0x0, { AGC_P_RZ, AGC_P_TOV } },  /* T6 xx */
    {  7, 0x2, 0x2, { AGC_P_RC, AGC_P_WA } },  /* T7 1x */
    {  7, 0x3, 0x1, { AGC_P_RC, AGC_P_WA } },  /* T7 01 */
    {  8, 0x0, 0x0, { AGC_P_RZ, AGC_P_WS, AGC_P_ST2, AGC_P_TSGN, AGC_P_RSTSTG } },  /* T8 xx */
    {  9, 0x0, 0x0, { AGC_P_RU, AGC_P_WB, AGC_P_WL } },  /* T9 xx */
    { 10, 0x2, 0x0, { AGC_P_RC, AGC_P_WL } },  /* T10 0x */
};

static const agc_pulse_row dv6_rows[] = {
    {  1, 0x0, 0x0, { AGC_P_L2GD, AGC_P_RB, AGC_P_PIFL, AGC_P_WYD, AGC_P_A2X } },  /* T1 xx */
    {  2, 0x0, 0x0, { AGC_P_RG, AGC_P_TSGU, AGC_P_CLXC, AGC_P_RB1F, AGC_P_WL, AGC_P_DVST } },  /* T2 xx */
    {  3, 0x0, 0x0, { AGC_P_RU, AGC_P_WB, AGC_P_STAGE } },  /* T3 xx */
    {  4, 0x0, 0x0, { AGC_P_L2GD, AGC_P_RB, AGC_P_PIFL, AGC_P_WYD, AGC_P_A2X } },  /* T4 xx */
    {  5, 0x0, 0x0, { AGC_P_RG, AGC_P_TSGU, AGC_P_CLXC, AGC_P_RB1F, AGC_P_WL } },  /* T5 xx */
    {  6, 0x0, 0x0, { AGC_P_RU, AGC_P_WB } },  /* T6 xx */
    {  7, 0x0, 0x0, { AGC_P_L2GD, AGC_P_RB, AGC_P_PIFL, AGC_P_WYD, AGC_P_A2X } },  /* T7 xx */
    {  8, 0x0, 0x0, { AGC_P_RG, AGC_P_TSGU, AGC_P_CLXC, AGC_P_RB1F, AGC_P_WL } },  /* T8 xx */
    {  9, 0x0, 0x0, { AGC_P_RU, AGC_P_WB } },  /* T9 xx */
    { 10, 0x0, 0x0, { AGC_P_L2GD, AGC_P_RB, AGC_P_PIFL, AGC_P_WYD, AGC_P_A2X } },  /* T10 xx */
    { 11, 0x0, 0x0, { AGC_P_RG, AGC_P_TSGU, AGC_P_CLXC, AGC_P_RB1F, AGC_P_WL } },  /* T11 xx */
    { 12, 0x0, 0x0, { AGC_P_RU, AGC_P_WB } },  /* T12 xx */
};

static const agc_pulse_row dv7_rows[] = {
    {  1, 0x0, 0x0, { AGC_P_L2GD, AGC_P_RB, AGC_P_PIFL, AGC_P_WYD, AGC_P_A2X } },  /* T1 xx */
    {  2, 0x0, 0x0, { AGC_P_RG, AGC_P_TSGU, AGC_P_CLXC, AGC_P_RB1F, AGC_P_WL, AGC_P_DVST } },  /* T2 xx */
    {  3, 0x0, 0x0, { AGC_P_RU, AGC_P_WB, AGC_P_STAGE } },  /* T3 xx */
    {  4, 0x0, 0x0, { AGC_P_L2GD, AGC_P_RB, AGC_P_PIFL, AGC_P_WYD, AGC_P_A2X } },  /* T4 xx */
    {  5, 0x0, 0x0, { AGC_P_RG, AGC_P_TSGU, AGC_P_CLXC, AGC_P_RB1F, AGC_P_WL } },  /* T5 xx */
    {  6, 0x0, 0x0, { AGC_P_RU, AGC_P_WB } },  /* T6 xx */
    {  7, 0x0, 0x0, { AGC_P_L2GD, AGC_P_RB, AGC_P_PIFL, AGC_P_WYD, AGC_P_A2X } },  /* T7 xx */
    {  8, 0x0, 0x0, { AGC_P_RG, AGC_P_TSGU, AGC_P_CLXC, AGC_P_RB1F, AGC_P_WL } },  /* T8 xx */
    {  9, 0x0, 0x0, { AGC_P_RU, AGC_P_WB } },  /* T9 xx */
    { 10, 0x0, 0x0, { AGC_P_L2GD, AGC_P_RB, AGC_P_PIFL, AGC_P_WYD, AGC_P_A2X } },  /* T10 xx */
    { 11, 0x0, 0x0, { AGC_P_RG, AGC_P_TSGU, AGC_P_CLXC, AGC_P_RB1F, AGC_P_WL } },  /* T11 xx */
    { 12, 0x0, 0x0, { AGC_P_RU, AGC_P_WB } },  /* T12 xx */
};

static const agc_pulse_row dxch0_rows[] = {
    {  1, 0x0, 0x0, { AGC_P_RL10BB, AGC_P_WS, AGC_P_WY12, AGC_P_MONEX, AGC_P_CI } },  /* T1 xx */
    {  2, 0x0, 0x0, { AGC_P_RSC, AGC_P_WG } },  /* T2 xx */
    {  3, 0x0, 0x0, { AGC_P_RL, AGC_P_WB } },  /* T3 xx */
    {  5, 0x0, 0x0, { AGC_P_RG, AGC_P_WL } },  /* T5 xx */
    {  7, 0x0, 0x0, { AGC_P_RB, AGC_P_WSC, AGC_P_WG } },  /* T7 xx */
    {  8, 0x0, 0x0, { AGC_P_RU, AGC_P_WS, AGC_P_WB } },  /* T8 xx */
    { 10, 0x0, 0x0, { AGC_P_ST1 } },  /* T10 xx */
};

static const agc_pulse_row dxch1_rows[] = {
    {  1, 0x0, 0x0, { AGC_P_RL10BB, AGC_P_WS } },  /* T1 xx */
    {  2, 0x0, 0x0, { AGC_P_RSC, AGC_P_WG } },  /* T2 xx */
    {  3, 0x0, 0x0, { AGC_P_RA, AGC_P_WB } },  /* T3 xx */
    {  5, 0x0, 0x0, { AGC_P_RG, AGC_P_WA } },  /* T5 xx */
    {  7, 0x0, 0x0, { AGC_P_RB, AGC_P_WSC, AGC_P_WG } },  /* T7 xx */
    {  8, 0x0, 0x0, { AGC_P_RZ, AGC_P_WS, AGC_P_ST2 } },  /* T8 xx */
};

static const agc_pulse_row goj1_rows[] = {
    {  2, 0x0, 0x0, { AGC_P_RSC, AGC_P_WG } },  /* T2 xx */
    {  8, 0x0, 0x0, { AGC_P_RSTRT, AGC_P_WS, AGC_P_WB } },  /* T8 xx */
};

static const agc_pulse_row incr0_rows[] = {
    {  1, 0x0, 0x0, { AGC_P_RL10BB, AGC_P_WS } },  /* T1 xx */
    {  2, 0x0, 0x0, { AGC_P_RSC, AGC_P_WG } },  /* T2 xx */
    {  5, 0x0, 0x0, { AGC_P_RG, AGC_P_WY, AGC_P_TSGN, AGC_P_TMZ, AGC_P_TPZG } },  /* T5 xx */
    {  6, 0x0, 0x0, { AGC_P_PONEX } },  /* T6 xx */
    {  7, 0x0, 0x0, { AGC_P_RU, AGC_P_WSC, AGC_P_WG, AGC_P_WOVR } },  /* T7 xx */
    {  8, 0x0, 0x0, { AGC_P_RZ, AGC_P_WS, AGC_P_ST2 } },  /* T8 xx */
};

static const agc_pulse_row lxch0_rows[] = {
    {  1, 0x0, 0x0, { AGC_P_RL10BB, AGC_P_WS } },  /* T1 xx */
    {  2, 0x0, 0x0, { AGC_P_RSC, AGC_P_WG } },  /* T2 xx */
    {  3, 0x0, 0x0, { AGC_P_RL, AGC_P_WB } },  /* T3 xx */
    {  5, 0x0, 0x0, { AGC_P_RG, AGC_P_WL } },  /* T5 xx */
    {  7, 0x0, 0x0, { AGC_P_RB, AGC_P_WSC, AGC_P_WG } },  /* T7 xx */
    {  8, 0x0, 0x0, { AGC_P_RZ, AGC_P_WS, AGC_P_ST2 } },  /* T8 xx */
};

static const agc_pulse_row mcdu_rows[] = {
    {  1, 0x0, 0x0, { AGC_P_RSCT, AGC_P_WS } },  /* T1 xx */
    {  2, 0x0, 0x0, { AGC_P_RSC, AGC_P_WG } },  /* T2 xx */
    {  5, 0x0, 0x0, { AGC_P_RG, AGC_P_WY, AGC_P_TSGN, AGC_P_TMZ, AGC_P_TPZG } },  /* T5 xx */
    {  6, 0x0, 0x0, { AGC_P_MONEX, AGC_P_CI } },  /* T6 xx */
    {  7, 0x0, 0x0, { AGC_P_RUS, AGC_P_WSC, AGC_P_WG, AGC_P_WOVR } },  /* T7 xx */
    {  8, 0x0, 0x0, { AGC_P_RB, AGC_P_WS } },  /* T8 xx */
};

static const agc_pulse_row minc_rows[] = {
    {  1, 0x0, 0x0, { AGC_P_RSCT, AGC_P_WS } },  /* T1 xx */
    {  2, 0x0, 0x0, { AGC_P_RSC, AGC_P_WG } },  /* T2 xx */
    {  5, 0x0, 0x0, { AGC_P_RG, AGC_P_WY, AGC_P_TSGN, AGC_P_TMZ, AGC_P_TPZG } },  /* T5 xx */
    {  6, 0x0, 0x0, { AGC_P_MONEX } },  /* T6 xx */
    {  7, 0x0, 0x0, { AGC_P_RU, AGC_P_WSC, AGC_P_WG, AGC_P_WOVR } },  /* T7 xx */
    {  8, 0x0, 0x0, { AGC_P_RB, AGC_P_WS } },  /* T8 xx */
};

static const agc_pulse_row mp0_rows[] = {
    {  2, 0x0, 0x0, { AGC_P_RSC, AGC_P_WG } },  /* T2 xx */
    {  3, 0x0, 0x0, { AGC_P_RA, AGC_P_WB, AGC_P_TSGN } },  /* T3 xx */
    {  4, 0x2, 0x0, { AGC_P_RB, AGC_P_WL } },  /* T4 0x */
    {  4, 0x2, 0x2, { AGC_P_RC, AGC_P_WL } },  /* T4 1x */
    {  7, 0x0, 0x0, { AGC_P_RG, AGC_P_WB, AGC_P_TSGN2 } },  /* T7 xx */
    {  8, 0x0, 0x0, { AGC_P_RZ, AGC_P_WS } },  /* T8 xx */
    {  9, 0x3, 0x0, { AGC_P_RB, AGC_P_WY } },  /* T9 00 */
    {  9, 0x3, 0x1, { AGC_P_RB, AGC_P_WY, AGC_P_CI } },  /* T9 01 */
    {  9, 0x3, 0x2, { AGC_P_RC, AGC_P_WY, AGC_P_CI } },  /* T9 10 */
    {  9, 0x3, 0x3, { AGC_P_RC, AGC_P_WY } },  /* T9 11 */
    { 10, 0x0, 0x0, { AGC_P_RU, AGC_P_WB, AGC_P_TSGN, AGC_P_ST1, AGC_P_NEACON } },  /* T10 xx */
    { 11, 0x2, 0x0, { AGC_P_WA } },  /* T11 0x */
    { 11, 0x2, 0x2, { AGC_P_RB1, AGC_P_R1C, AGC_P_WA, AGC_P_L16 } },  /* T11 1x */
};

static const agc_pulse_row mp1_rows[] = {
    {  1, 0x0, 0x0, { AGC_P_ZIP } },  /* T1 xx */
    {  2, 0x0, 0x0, { AGC_P_ZAP } },  /* T2 xx */
    {  3, 0x0, 0x0, { AGC_P_ZIP } },  /* T3 xx */
    {  4, 0x0, 0x0, { AGC_P_ZAP } },  /* T4 xx */
    {  5, 0x0, 0x0, { AGC_P_ZIP } },  /* T5 xx */
    {  6, 0x0, 0x0, { AGC_P_ZAP } },  /* T6 xx */
    {  7, 0x0, 0x0, { AGC_P_ZIP } },  /* T7 xx */
    {  8, 0x0, 0x0, { AGC_P_ZAP } },  /* T8 xx */
    {  9, 0x0, 0x0, { AGC_P_ZIP } },  /* T9 xx */
    { 10, 0x0, 0x0, { AGC_P_ZAP, AGC_P_ST1, AGC_P_ST2 } },  /* T10 xx */
    { 11, 0x0, 0x0, { AGC_P_ZIP } },  /* T11 xx */
};

static const agc_pulse_row mp3_rows[] = {
    {  1, 0x0, 0x0, { AGC_P_ZAP } },  /* T1 xx */
    {  2, 0x0, 0x0, { AGC_P_ZIP, AGC_P_NISQ } },  /* T2 xx */
    {  3, 0x0, 0x0, { AGC_P_ZAP } },  /* T3 xx */
    {  4, 0x0, 0x0, { AGC_P_RSC, AGC_P_WG } },  /* T4 xx */
    {  5, 0x0, 0x0, { AGC_P_RZ, AGC_P_WY12, AGC_P_CI } },  /* T5 xx */
    {  6, 0x0, 0x0, { AGC_P_RU, AGC_P_WZ, AGC_P_TL15, AGC_P_NEACOF } },  /* T6 xx */
    {  7, 0x2, 0x2, { AGC_P_RB, AGC_P_WY, AGC_P_A2X } },  /* T7 1x */
    {  8, 0x0, 0x0, { AGC_P_RAD, AGC_P_WB, AGC_P_WS } },  /* T8 xx */
    {  9, 0x0, 0x0, { AGC_P_RA } },  /* T9 xx */
    { 10, 0x0, 0x0, { AGC_P_RL } },  /* T10 xx */
    { 11, 0x2, 0x2, { AGC_P_RU, AGC_P_WA } },  /* T11 1x */
};

static const agc_pulse_row msk0_rows[] = {
    {  2, 0x0, 0x0, { AGC_P_RSC, AGC_P_WG } },  /* T2 xx */
    {  3, 0x0, 0x0, { AGC_P_RA, AGC_P_WB } },  /* T3 xx */
    {  4, 0x0, 0x0, { AGC_P_RC, AGC_P_WA } },  /* T4 xx */
    {  7, 0x0, 0x0, { AGC_P_RG, AGC_P_WB } },  /* T7 xx */
    {  8, 0x0, 0x0, { AGC_P_RZ, AGC_P_WS, AGC_P_ST2 } },  /* T8 xx */
    {  9, 0x0, 0x0, { AGC_P_RC, AGC_P_RA, AGC_P_WY } },  /* T9 xx */
    { 10, 0x0, 0x0, { AGC_P_RU, AGC_P_WB } },  /* T10 xx */
    { 11, 0x0, 0x0, { AGC_P_RC, AGC_P_WA } },  /* T11 xx */
};

static const agc_pulse_row msu0_rows[] = {
    {  1, 0x0, 0x0, { AGC_P_RL10BB, AGC_P_WS } },  /* T1 xx */
    {  2, 0x0, 0x0, { AGC_P_RSC, AGC_P_WG } },  /* T2 xx */
    {  5, 0x0, 0x0, { AGC_P_RG, AGC_P_WB } },  /* T5 xx */
    {  6, 0x0, 0x0, { AGC_P_RC, AGC_P_WY, AGC_P_CI, AGC_P_A2X } },  /* T6 xx */
    {  7, 0x0, 0x0, { AGC_P_RUS, AGC_P_WA, AGC_P_TSGN } },  /* T7 xx */
    {  8, 0x0, 0x0, { AGC_P_RZ, AGC_P_WS, AGC_P_ST2 } },  /* T8 xx */
    {  9, 0x0, 0x0, { AGC_P_RB, AGC_P_WG } },  /* T9 xx */
    { 10, 0x2, 0x2, { AGC_P_RA, AGC_P_WY, AGC_P_MONEX } },  /* T10 1x */
    { 11, 0x0, 0x0, { AGC_P_RUS, AGC_P_WA } },  /* T11 xx */
};

static const agc_pulse_row ndx0_rows[] = {
    {  2, 0x0, 0x0, { AGC_P_RSC, AGC_P_WG } },  /* T2 xx */
    {  5, 0x0, 0x0, { AGC_P_TRSM } },  /* T5 xx */
    {  7, 0x0, 0x0, { AGC_P_RG, AGC_P_WB } },  /* T7 xx */
    {  8, 0x0, 0x0, { AGC_P_RZ, AGC_P_WS } },  /* T8 xx */
    {  9, 0x0, 0x0, { AGC_P_RB, AGC_P_WG } },  /* T9 xx */
    { 10, 0x0, 0x0, { AGC_P_ST1 } },  /* T10 xx */
};

static const agc_pulse_row ndx1_rows[] = {
    {  1, 0x0, 0x0, { AGC_P_RZ, AGC_P_WY12, AGC_P_CI } },  /* T1 xx */
    {  2, 0x0, 0x0, { AGC_P_RSC, AGC_P_WG, AGC_P_NISQ } },  /* T2 xx */
    {  3, 0x0, 0x0, { AGC_P_RB, AGC_P_WZ } },  /* T3 xx */
    {  4, 0x0, 0x0, { AGC_P_RA, AGC_P_WB } },  /* T4 xx */
    {  5, 0x0, 0x0, { AGC_P_RZ, AGC_P_WA } },  /* T5 xx */
    {  6, 0x0, 0x0, { AGC_P_RU, AGC_P_WZ } },  /* T6 xx */
    {  7, 0x0, 0x0, { AGC_P_RG, AGC_P_WY, AGC_P_A2X } },  /* T7 xx */
    {  8, 0x0, 0x0, { AGC_P_RU, AGC_P_WS } },  /* T8 xx */
    {  9, 0x0, 0x0, { AGC_P_RB, AGC_P_WA } },  /* T9 xx */
    { 10, 0x0, 0x0, { AGC_P_RU, AGC_P_WB } },  /* T10 xx */
};

static const agc_pulse_row ndxx0_rows[] = {
    {  2, 0x0, 0x0, { AGC_P_RSC, AGC_P_WG } },  /* T2 xx */
    {  7, 0x0, 0x0, { AGC_P_RG, AGC_P_WB } },  /* T7 xx */
    {  8, 0x0, 0x0, { AGC_P_RZ, AGC_P_WS } },  /* T8 xx */
    {  9, 0x0, 0x0, { AGC_P_RB, AGC_P_WG } },  /* T9 xx */
    { 10, 0x0, 0x0, { AGC_P_ST1 } },  /* T10 xx */
};

static const agc_pulse_row ndxx1_rows[] = {
    {  1, 0x0, 0x0, { AGC_P_RZ, AGC_P_WY12, AGC_P_CI } },  /* T1 xx */
    {  2, 0x0, 0x0, { AGC_P_RSC, AGC_P_WG, AGC_P_NISQ } },  /* T2 xx */
    {  3, 0x0, 0x0, { AGC_P_RB, AGC_P_WZ } },  /* T3 xx */
    {  4, 0x0, 0x0, { AGC_P_RA, AGC_P_WB } },  /* T4 xx */
    {  5, 0x0, 0x0, { AGC_P_RZ, AGC_P_WA } },  /* T5 xx */
    {  6, 0x0, 0x0, { AGC_P_RU, AGC_P_WZ } },  /* T6 xx */
    {  7, 0x0, 0x0, { AGC_P_RG, AGC_P_WY, AGC_P_A2X } },  /* T7 xx */
    {  8, 0x0, 0x0, { AGC_P_RU, AGC_P_WS } },  /* T8 xx */
    {  9, 0x0, 0x0, { AGC_P_RB, AGC_P_WA } },  /* T9 xx */
    { 10, 0x0, 0x0, { AGC_P_RU, AGC_P_WB, AGC_P_EXT } },  /* T10 xx */
};

static const agc_pulse_row pcdu_rows[] = {
    {  1, 0x0, 0x0, { AGC_P_RSCT, AGC_P_WS } },  /* T1 xx */
    {  2, 0x0, 0x0, { AGC_P_RSC, AGC_P_WG } },  /* T2 xx */
    {  5, 0x0, 0x0, { AGC_P_RG, AGC_P_WY, AGC_P_TSGN, AGC_P_TMZ, AGC_P_TPZG } },  /* T5 xx */
    {  6, 0x0, 0x0, { AGC_P_CI } },  /* T6 xx */
    {  7, 0x0, 0x0, { AGC_P_RUS, AGC_P_WSC, AGC_P_WG, AGC_P_WOVR } },  /* T7 xx */
    {  8, 0x0, 0x0, { AGC_P_RB, AGC_P_WS } },  /* T8 xx */
};

static const agc_pulse_row pinc_rows[] = {
    {  1, 0x0, 0x0, { AGC_P_RSCT, AGC_P_WS } },  /* T1 xx */
    {  2, 0x0, 0x0, { AGC_P_RSC, AGC_P_WG } },  /* T2 xx */
    {  5, 0x0, 0x0, { AGC_P_RG, AGC_P_WY, AGC_P_TSGN, AGC_P_TMZ, AGC_P_TPZG } },  /* T5 xx */
    {  6, 0x0, 0x0, { AGC_P_PONEX } },  /* T6 xx */
    {  7, 0x0, 0x0, { AGC_P_RU, AGC_P_WSC, AGC_P_WG, AGC_P_WOVR } },  /* T7 xx */
    {  8, 0x0, 0x0, { AGC_P_RB, AGC_P_WS } },  /* T8 xx */
};

static const agc_pulse_row qxch0_rows[] = {
    {  1, 0x0, 0x0, { AGC_P_RL10BB, AGC_P_WS } },  /* T1 xx */
    {  2, 0x0, 0x0, { AGC_P_RSC, AGC_P_WG } },  /* T2 xx */
    {  3, 0x0, 0x0, { AGC_P_RQ, AGC_P_WB } },  /* T3 xx */
    {  5, 0x0, 0x0, { AGC_P_RG, AGC_P_WQ } },  /* T5 xx */
    {  7, 0x0, 0x0, { AGC_P_RB, AGC_P_WSC, AGC_P_WG } },  /* T7 xx */
    {  8, 0x0, 0x0, { AGC_P_RZ, AGC_P_WS, AGC_P_ST2 } },  /* T8 xx */
};

static const agc_pulse_row rand0_rows[] = {
    {  1, 0x0, 0x0, { AGC_P_RL10BB, AGC_P_WS } },  /* T1 xx */
    {  2, 0x0, 0x0, { AGC_P_RA, AGC_P_WB } },  /* T2 xx */
    {  3, 0x0, 0x0, { AGC_P_RC, AGC_P_WY } },  /* T3 xx */
    {  4, 0x0, 0x0, { AGC_P_RCH, AGC_P_WB } },  /* T4 xx */
    {  5, 0x0, 0x0, { AGC_P_RC, AGC_P_RU, AGC_P_WA } },  /* T5 xx */
    {  6, 0x0, 0x0, { AGC_P_RA, AGC_P_WB } },  /* T6 xx */
    {  7, 0x0, 0x0, { AGC_P_RC, AGC_P_WA } },  /* T7 xx */
    {  8, 0x0, 0x0, { AGC_P_RZ, AGC_P_WS, AGC_P_ST2 } },  /* T8 xx */
};

static const agc_pulse_row read0_rows[] = {
    {  1, 0x0, 0x0, { AGC_P_RL10BB, AGC_P_WS } },  /* T1 xx */
    {  2, 0x0, 0x0, { AGC_P_RA, AGC_P_WB } },  /* T2 xx */
    {  3, 0x0, 0x0, { AGC_P_WY } },  /* T3 xx */
    {  4, 0x0, 0x0, { AGC_P_RCH, AGC_P_WB } },  /* T4 xx */
    {  5, 0x0, 0x0, { AGC_P_RB, AGC_P_WA } },  /* T5 xx */
    {  6, 0x0, 0x0, { AGC_P_RA, AGC_P_WB } },  /* T6 xx */
    {  8, 0x0, 0x0, { AGC_P_RZ, AGC_P_WS, AGC_P_ST2 } },  /* T8 xx */
};

static const agc_pulse_row ror0_rows[] = {
    {  1, 0x0, 0x0, { AGC_P_RL10BB, AGC_P_WS } },  /* T1 xx */
    {  2, 0x0, 0x0, { AGC_P_RA, AGC_P_WB } },  /* T2 xx */
    {  3, 0x0, 0x0, { AGC_P_RB, AGC_P_WY } },  /* T3 xx */
    {  4, 0x0, 0x0, { AGC_P_RCH, AGC_P_WB } },  /* T4 xx */
    {  5, 0x0, 0x0, { AGC_P_RB, AGC_P_RU, AGC_P_WA } },  /* T5 xx */
    {  6, 0x0, 0x0, { AGC_P_RA, AGC_P_WB } },  /* T6 xx */
    {  8, 0x0, 0x0, { AGC_P_RZ, AGC_P_WS, AGC_P_ST2 } },  /* T8 xx */
};

static const agc_pulse_row rsm3_rows[] = {
    {  1, 0x0, 0x0, { AGC_P_R15, AGC_P_WS } },  /* T1 xx */
    {  2, 0x0, 0x0, { AGC_P_RSC, AGC_P_WG, AGC_P_NISQ } },  /* T2 xx */
    {  5, 0x0, 0x0, { AGC_P_RG, AGC_P_WZ } },  /* T5 xx */
    {  6, 0x0, 0x0, { AGC_P_RB, AGC_P_WG } },  /* T6 xx */
    {  8, 0x0, 0x0, { AGC_P_RAD, AGC_P_WB, AGC_P_WS, AGC_P_CLRIIP } },  /* T8 xx */
};

static const agc_pulse_row rupt0_rows[] = {
    {  1, 0x0, 0x0, { AGC_P_R15, AGC_P_WS } },  /* T1 xx */
    {  2, 0x0, 0x0, { AGC_P_RSC, AGC_P_WG } },  /* T2 xx */
    {  9, 0x0, 0x0, { AGC_P_RZ, AGC_P_WG } },  /* T9 xx */
    { 10, 0x0, 0x0, { AGC_P_ST1 } },  /* T10 xx */
};

static const agc_pulse_row rupt1_rows[] = {
    {  1, 0x0, 0x0, { AGC_P_R15, AGC_P_RB2, AGC_P_WS } },  /* T1 xx */
    {  2, 0x0, 0x0, { AGC_P_RSC, AGC_P_WG } },  /* T2 xx */
    {  3, 0x0, 0x0, { AGC_P_RRPA, AGC_P_WZ } },  /* T3 xx */
    {  8, 0x0, 0x0, { AGC_P_RZ, AGC_P_WS, AGC_P_ST2 } },  /* T8 xx */
    {  9, 0x0, 0x0, { AGC_P_RB, AGC_P_WG, AGC_P_KRPT } },  /* T9 xx */
};

static const agc_pulse_row rxor0_rows[] = {
    {  1, 0x0, 0x0, { AGC_P_RL10BB, AGC_P_WS } },  /* T1 xx */
    {  2, 0x0, 0x0, { AGC_P_RA, AGC_P_WB } },  /* T2 xx */
    {  3, 0x0, 0x0, { AGC_P_RC, AGC_P_RCH, AGC_P_WY } },  /* T3 xx */
    {  4, 0x0, 0x0, { AGC_P_RCH, AGC_P_WB } },  /* T4 xx */
    {  5, 0x0, 0x0, { AGC_P_RA, AGC_P_RC, AGC_P_WG } },  /* T5 xx */
    {  7, 0x0, 0x0, { AGC_P_RG, AGC_P_WB } },  /* T7 xx */
    {  8, 0x0, 0x0, { AGC_P_RZ, AGC_P_WS, AGC_P_ST2 } },  /* T8 xx */
    {  9, 0x0, 0x0, { AGC_P_RC, AGC_P_WG } },  /* T9 xx */
    { 10, 0x0, 0x0, { AGC_P_RU, AGC_P_WB } },  /* T10 xx */
    { 11, 0x0, 0x0, { AGC_P_RC, AGC_P_RG, AGC_P_WA } },  /* T11 xx */
};

static const agc_pulse_row shanc_rows[] = {
    {  1, 0x0, 0x0, { AGC_P_RSCT, AGC_P_WS } },  /* T1 xx */
    {  2, 0x0, 0x0, { AGC_P_RSC, AGC_P_WG } },  /* T2 xx */
    {  5, 0x0, 0x0, { AGC_P_RG, AGC_P_WYD, AGC_P_TSGN, AGC_P_CI } },  /* T5 xx */
    {  7, 0x0, 0x0, { AGC_P_RUS, AGC_P_WSC, AGC_P_WG, AGC_P_WOVR } },  /* T7 xx */
    {  8, 0x0, 0x0, { AGC_P_RB, AGC_P_WS } },  /* T8 xx */
};

static const agc_pulse_row shinc_rows[] = {
    {  1, 0x0, 0x0, { AGC_P_RSCT, AGC_P_WS } },  /* T1 xx */
    {  2, 0x0, 0x0, { AGC_P_RSC, AGC_P_WG } },  /* T2 xx */
    {  5, 0x0, 0x0, { AGC_P_RG, AGC_P_WYD, AGC_P_TSGN } },  /* T5 xx */
    {  7, 0x0, 0x0, { AGC_P_RU, AGC_P_WSC, AGC_P_WG, AGC_P_WOVR } },  /* T7 xx */
    {  8, 0x0, 0x0, { AGC_P_RB, AGC_P_WS } },  /* T8 xx */
};

static const agc_pulse_row std2_rows[] = {
    {  1, 0x0, 0x0, { AGC_P_RZ, AGC_P_WY12, AGC_P_CI } },  /* T1 xx */
    {  2, 0x0, 0x0, { AGC_P_RSC, AGC_P_WG, AGC_P_NISQ } },  /* T2 xx */
    {  6, 0x0, 0x0, { AGC_P_RU, AGC_P_WZ } },  /* T6 xx */
    {  8, 0x0, 0x0, { AGC_P_RAD, AGC_P_WB, AGC_P_WS } },  /* T8 xx */
};

static const agc_pulse_row su0_rows[] = {
    {  2, 0x0, 0x0, { AGC_P_RSC, AGC_P_WG } },  /* T2 xx */
    {  7, 0x0, 0x0, { AGC_P_RG, AGC_P_WB } },  /* T7 xx */
    {  8, 0x0, 0x0, { AGC_P_RZ, AGC_P_WS, AGC_P_ST2 } },  /* T8 xx */
    {  9, 0x0, 0x0, { AGC_P_RB, AGC_P_WG } },  /* T9 xx */
    { 10, 0x0, 0x0, { AGC_P_RC, AGC_P_WY, AGC_P_A2X } },  /* T10 xx */
    { 11, 0x0, 0x0, { AGC_P_RU, AGC_P_WA } },  /* T11 xx */
};

static const agc_pulse_row tc0_rows[] = {
    {  1, 0x0, 0x0, { AGC_P_RB, AGC_P_WY12, AGC_P_CI } },  /* T1 xx */
    {  2, 0x0, 0x0, { AGC_P_RSC, AGC_P_WG, AGC_P_NISQ } },  /* T2 xx */
    {  3, 0x0, 0x0, { AGC_P_RZ, AGC_P_WQ } },  /* T3 xx */
    {  6, 0x0, 0x0, { AGC_P_RU, AGC_P_WZ } },  /* T6 xx */
    {  8, 0x0, 0x0, { AGC_P_RAD, AGC_P_WB, AGC_P_WS } },  /* T8 xx */
};

static const agc_pulse_row tcf0_rows[] = {
    {  1, 0x0, 0x0, { AGC_P_RB, AGC_P_WY12, AGC_P_CI } },  /* T1 xx */
    {  2, 0x0, 0x0, { AGC_P_RSC, AGC_P_WG, AGC_P_NISQ } },  /* T2 xx */
    {  6, 0x0, 0x0, { AGC_P_RU, AGC_P_WZ } },  /* T6 xx */
    {  8, 0x0, 0x0, { AGC_P_RAD, AGC_P_WB, AGC_P_WS } },  /* T8 xx */
};

static const agc_pulse_row ts0_rows[] = {
    {  1, 0x0, 0x0, { AGC_P_RL10BB, AGC_P_WS } },  /* T1 xx */
    {  2, 0x0, 0x0, { AGC_P_RSC, AGC_P_WG } },  /* T2 xx */
    {  3, 0x0, 0x0, { AGC_P_RA, AGC_P_WB, AGC_P_TOV } },  /* T3 xx */
    {  4, 0x3, 0x0, { AGC_P_RZ, AGC_P_WY12 } },  /* T4 00 */
    {  4, 0x3, 0x1, { AGC_P_RZ, AGC_P_WY12, AGC_P_CI } },  /* T4 01 */
    {  4, 0x3, 0x2, { AGC_P_RZ, AGC_P_WY12, AGC_P_CI } },  /* T4 10 */
    {  4, 0x3, 0x3, { AGC_P_RZ, AGC_P_WY12 } },  /* T4 11 */
    {  5, 0x3, 0x1, { AGC_P_RB1, AGC_P_WA } },  /* T5 01 */
    {  5, 0x3, 0x2, { AGC_P_R1C, AGC_P_WA } },  /* T5 10 */
    {  6, 0x0, 0x0, { AGC_P_RU, AGC_P_WZ } },  /* T6 xx */
    {  7, 0x0, 0x0, { AGC_P_RB, AGC_P_WSC, AGC_P_WG } },  /* T7 xx */
    {  8, 0x0, 0x0, { AGC_P_RZ, AGC_P_WS, AGC_P_ST2 } },  /* T8 xx */
};

static const agc_pulse_row wand0_rows[] = {
    {  1, 0x0, 0x0, { AGC_P_RL10BB, AGC_P_WS } },  /* T1 xx */
    {  2, 0x0, 0x0, { AGC_P_RA, AGC_P_WB } },  /* T2 xx */
    {  3, 0x0, 0x0, { AGC_P_RC, AGC_P_WY } },  /* T3 xx */
    {  4, 0x0, 0x0, { AGC_P_RCH, AGC_P_WB } },  /* T4 xx */
    {  5, 0x0, 0x0, { AGC_P_RC, AGC_P_RU, AGC_P_WA } },  /* T5 xx */
    {  6, 0x0, 0x0, { AGC_P_RA, AGC_P_WB } },  /* T6 xx */
    {  7, 0x0, 0x0, { AGC_P_RC, AGC_P_WA, AGC_P_WCH } },  /* T7 xx */
    {  8, 0x0, 0x0, { AGC_P_RZ, AGC_P_WS, AGC_P_ST2 } },  /* T8 xx */
};

static const agc_pulse_row wor0_rows[] = {
    {  1, 0x0, 0x0, { AGC_P_RL10BB, AGC_P_WS } },  /* T1 xx */
    {  2, 0x0, 0x0, { AGC_P_RA, AGC_P_WB } },  /* T2 xx */
    {  3, 0x0, 0x0, { AGC_P_RB, AGC_P_WY } },  /* T3 xx */
    {  4, 0x0, 0x0, { AGC_P_RCH, AGC_P_WB } },  /* T4 xx */
    {  5, 0x0, 0x0, { AGC_P_RB, AGC_P_RU, AGC_P_WA, AGC_P_WCH } },  /* T5 xx */
    {  6, 0x0, 0x0, { AGC_P_RA, AGC_P_WB } },  /* T6 xx */
    {  8, 0x0, 0x0, { AGC_P_RZ, AGC_P_WS, AGC_P_ST2 } },  /* T8 xx */
};

static const agc_pulse_row write0_rows[] = {
    {  1, 0x0, 0x0, { AGC_P_RL10BB, AGC_P_WS } },  /* T1 xx */
    {  2, 0x0, 0x0, { AGC_P_RA, AGC_P_WB, AGC_P_WG } },  /* T2 xx */
    {  3, 0x0, 0x0, { AGC_P_WY } },  /* T3 xx */
    {  4, 0x0, 0x0, { AGC_P_RCH, AGC_P_WB } },  /* T4 xx */
    {  5, 0x0, 0x0, { AGC_P_RA, AGC_P_WCH } },  /* T5 xx */
    {  6, 0x0, 0x0, { AGC_P_RA, AGC_P_WB } },  /* T6 xx */
    {  8, 0x0, 0x0, { AGC_P_RZ, AGC_P_WS, AGC_P_ST2 } },  /* T8 xx */
};

static const agc_pulse_row xch0_rows[] = {
    {  1, 0x0, 0x0, { AGC_P_RL10BB, AGC_P_WS } },  /* T1 xx */
    {  2, 0x0, 0x0, { AGC_P_RSC, AGC_P_WG } },  /* T2 xx */
    {  3, 0x0, 0x0, { AGC_P_RA, AGC_P_WB } },  /* T3 xx */
    {  5, 0x0, 0x0, { AGC_P_RG, AGC_P_WA } },  /* T5 xx */
    {  7, 0x0, 0x0, { AGC_P_RB, AGC_P_WSC, AGC_P_WG } },  /* T7 xx */
    {  8, 0x0, 0x0, { AGC_P_RZ, AGC_P_WS, AGC_P_ST2 } },  /* T8 xx */
};

const agc_subinst agc_subinst_table[] = {
    { "STD2", 0, 2, false, 000, 0000, std2_rows, (uint8_t)(sizeof std2_rows / sizeof *std2_rows) },
    { "TC0", AGC_SEQ_TRANSFER, 0, false, 070, 0000, tc0_rows, (uint8_t)(sizeof tc0_rows / sizeof *tc0_rows) },
    { "GOJ1", 0, 1, false, 070, 0000, goj1_rows, (uint8_t)(sizeof goj1_rows / sizeof *goj1_rows) },
    { "CCS0", 0, 0, false, 076, 0010, ccs0_rows, (uint8_t)(sizeof ccs0_rows / sizeof *ccs0_rows) },
    { "TCF0", AGC_SEQ_TRANSFER, 0, false, 076, 0012, tcf0_rows, (uint8_t)(sizeof tcf0_rows / sizeof *tcf0_rows) },
    { "TCF0", AGC_SEQ_TRANSFER, 0, false, 076, 0014, tcf0_rows, (uint8_t)(sizeof tcf0_rows / sizeof *tcf0_rows) },
    { "TCF0", AGC_SEQ_TRANSFER, 0, false, 076, 0016, tcf0_rows, (uint8_t)(sizeof tcf0_rows / sizeof *tcf0_rows) },
    { "DAS0", 0, 0, false, 076, 0020, das0_rows, (uint8_t)(sizeof das0_rows / sizeof *das0_rows) },
    { "DAS1", 0, 1, false, 076, 0020, das1_rows, (uint8_t)(sizeof das1_rows / sizeof *das1_rows) },
    { "LXCH0", 0, 0, false, 076, 0022, lxch0_rows, (uint8_t)(sizeof lxch0_rows / sizeof *lxch0_rows) },
    { "INCR0", 0, 0, false, 076, 0024, incr0_rows, (uint8_t)(sizeof incr0_rows / sizeof *incr0_rows) },
    { "ADS0", 0, 0, false, 076, 0026, ads0_rows, (uint8_t)(sizeof ads0_rows / sizeof *ads0_rows) },
    { "CA0", 0, 0, false, 070, 0030, ca0_rows, (uint8_t)(sizeof ca0_rows / sizeof *ca0_rows) },
    { "CS0", 0, 0, false, 070, 0040, cs0_rows, (uint8_t)(sizeof cs0_rows / sizeof *cs0_rows) },
    { "NDX0", 0, 0, false, 076, 0050, ndx0_rows, (uint8_t)(sizeof ndx0_rows / sizeof *ndx0_rows) },
    { "NDX1", 0, 1, false, 076, 0050, ndx1_rows, (uint8_t)(sizeof ndx1_rows / sizeof *ndx1_rows) },
    { "RSM3", 0, 3, false, 076, 0050, rsm3_rows, (uint8_t)(sizeof rsm3_rows / sizeof *rsm3_rows) },
    { "DXCH0", 0, 0, false, 076, 0052, dxch0_rows, (uint8_t)(sizeof dxch0_rows / sizeof *dxch0_rows) },
    { "DXCH1", 0, 1, false, 076, 0052, dxch1_rows, (uint8_t)(sizeof dxch1_rows / sizeof *dxch1_rows) },
    { "TS0", 0, 0, false, 076, 0054, ts0_rows, (uint8_t)(sizeof ts0_rows / sizeof *ts0_rows) },
    { "XCH0", 0, 0, false, 076, 0056, xch0_rows, (uint8_t)(sizeof xch0_rows / sizeof *xch0_rows) },
    { "AD0", 0, 0, false, 070, 0060, ad0_rows, (uint8_t)(sizeof ad0_rows / sizeof *ad0_rows) },
    { "MSK0", 0, 0, false, 070, 0070, msk0_rows, (uint8_t)(sizeof msk0_rows / sizeof *msk0_rows) },
    { "READ0", 0, 0, true, 077, 0000, read0_rows, (uint8_t)(sizeof read0_rows / sizeof *read0_rows) },
    { "WRITE0", 0, 0, true, 077, 0001, write0_rows, (uint8_t)(sizeof write0_rows / sizeof *write0_rows) },
    { "RAND0", 0, 0, true, 077, 0002, rand0_rows, (uint8_t)(sizeof rand0_rows / sizeof *rand0_rows) },
    { "WAND0", 0, 0, true, 077, 0003, wand0_rows, (uint8_t)(sizeof wand0_rows / sizeof *wand0_rows) },
    { "ROR0", 0, 0, true, 077, 0004, ror0_rows, (uint8_t)(sizeof ror0_rows / sizeof *ror0_rows) },
    { "WOR0", 0, 0, true, 077, 0005, wor0_rows, (uint8_t)(sizeof wor0_rows / sizeof *wor0_rows) },
    { "RXOR0", 0, 0, true, 077, 0006, rxor0_rows, (uint8_t)(sizeof rxor0_rows / sizeof *rxor0_rows) },
    { "RUPT0", 0, 0, true, 077, 0007, rupt0_rows, (uint8_t)(sizeof rupt0_rows / sizeof *rupt0_rows) },
    { "RUPT1", 0, 1, true, 077, 0007, rupt1_rows, (uint8_t)(sizeof rupt1_rows / sizeof *rupt1_rows) },
    { "DV0", 0, 0, true, 076, 0010, dv0_rows, (uint8_t)(sizeof dv0_rows / sizeof *dv0_rows) },
    { "DV1", 0, 1, true, 076, 0010, dv1_rows, (uint8_t)(sizeof dv1_rows / sizeof *dv1_rows) },
    { "DV3", 0, 3, true, 076, 0010, dv3_rows, (uint8_t)(sizeof dv3_rows / sizeof *dv3_rows) },
    { "DV7", 0, 7, true, 076, 0010, dv7_rows, (uint8_t)(sizeof dv7_rows / sizeof *dv7_rows) },
    { "DV6", 0, 6, true, 076, 0010, dv6_rows, (uint8_t)(sizeof dv6_rows / sizeof *dv6_rows) },
    { "DV4", 0, 4, true, 076, 0010, dv4_rows, (uint8_t)(sizeof dv4_rows / sizeof *dv4_rows) },
    { "BZF0", 0, 0, true, 076, 0012, bzf0_rows, (uint8_t)(sizeof bzf0_rows / sizeof *bzf0_rows) },
    { "BZF0", 0, 0, true, 076, 0014, bzf0_rows, (uint8_t)(sizeof bzf0_rows / sizeof *bzf0_rows) },
    { "BZF0", 0, 0, true, 076, 0016, bzf0_rows, (uint8_t)(sizeof bzf0_rows / sizeof *bzf0_rows) },
    { "MSU0", 0, 0, true, 076, 0020, msu0_rows, (uint8_t)(sizeof msu0_rows / sizeof *msu0_rows) },
    { "QXCH0", 0, 0, true, 076, 0022, qxch0_rows, (uint8_t)(sizeof qxch0_rows / sizeof *qxch0_rows) },
    { "AUG0", 0, 0, true, 076, 0024, aug0_rows, (uint8_t)(sizeof aug0_rows / sizeof *aug0_rows) },
    { "DIM0", 0, 0, true, 076, 0026, dim0_rows, (uint8_t)(sizeof dim0_rows / sizeof *dim0_rows) },
    { "DCA0", 0, 0, true, 070, 0030, dca0_rows, (uint8_t)(sizeof dca0_rows / sizeof *dca0_rows) },
    { "DCA1", 0, 1, true, 070, 0030, dca1_rows, (uint8_t)(sizeof dca1_rows / sizeof *dca1_rows) },
    { "DCS0", 0, 0, true, 070, 0040, dcs0_rows, (uint8_t)(sizeof dcs0_rows / sizeof *dcs0_rows) },
    { "DCS1", 0, 1, true, 070, 0040, dcs1_rows, (uint8_t)(sizeof dcs1_rows / sizeof *dcs1_rows) },
    { "NDXX0", 0, 0, true, 070, 0050, ndxx0_rows, (uint8_t)(sizeof ndxx0_rows / sizeof *ndxx0_rows) },
    { "NDXX1", 0, 1, true, 070, 0050, ndxx1_rows, (uint8_t)(sizeof ndxx1_rows / sizeof *ndxx1_rows) },
    { "SU0", 0, 0, true, 076, 0060, su0_rows, (uint8_t)(sizeof su0_rows / sizeof *su0_rows) },
    { "BZMF0", 0, 0, true, 076, 0062, bzmf0_rows, (uint8_t)(sizeof bzmf0_rows / sizeof *bzmf0_rows) },
    { "BZMF0", 0, 0, true, 076, 0064, bzmf0_rows, (uint8_t)(sizeof bzmf0_rows / sizeof *bzmf0_rows) },
    { "BZMF0", 0, 0, true, 076, 0066, bzmf0_rows, (uint8_t)(sizeof bzmf0_rows / sizeof *bzmf0_rows) },
    { "MP0", 0, 0, true, 070, 0070, mp0_rows, (uint8_t)(sizeof mp0_rows / sizeof *mp0_rows) },
    { "MP1", 0, 1, true, 070, 0070, mp1_rows, (uint8_t)(sizeof mp1_rows / sizeof *mp1_rows) },
    { "MP3", AGC_SEQ_MP3, 3, true, 070, 0070, mp3_rows, (uint8_t)(sizeof mp3_rows / sizeof *mp3_rows) },
    { "STD2", 0, 2, true, 000, 0000, std2_rows, (uint8_t)(sizeof std2_rows / sizeof *std2_rows) },
};
const size_t agc_subinst_count = sizeof agc_subinst_table / sizeof *agc_subinst_table;

/* Involuntary sequences, injected by priority control rather than decoded. */
const agc_subinst agc_subinst_dinc = { "DINC", 0, 0, false, 0, 0, dinc_rows, (uint8_t)(sizeof dinc_rows / sizeof *dinc_rows) };
const agc_subinst agc_subinst_mcdu = { "MCDU", 0, 0, false, 0, 0, mcdu_rows, (uint8_t)(sizeof mcdu_rows / sizeof *mcdu_rows) };
const agc_subinst agc_subinst_minc = { "MINC", 0, 0, false, 0, 0, minc_rows, (uint8_t)(sizeof minc_rows / sizeof *minc_rows) };
const agc_subinst agc_subinst_pcdu = { "PCDU", 0, 0, false, 0, 0, pcdu_rows, (uint8_t)(sizeof pcdu_rows / sizeof *pcdu_rows) };
const agc_subinst agc_subinst_pinc = { "PINC", 0, 0, false, 0, 0, pinc_rows, (uint8_t)(sizeof pinc_rows / sizeof *pinc_rows) };
const agc_subinst agc_subinst_shanc = { "SHANC", 0, 0, false, 0, 0, shanc_rows, (uint8_t)(sizeof shanc_rows / sizeof *shanc_rows) };
const agc_subinst agc_subinst_shinc = { "SHINC", 0, 0, false, 0, 0, shinc_rows, (uint8_t)(sizeof shinc_rows / sizeof *shinc_rows) };
