/* GENERATED by tools/gen_block1_tables.py — do not edit by hand.
 *
 * The Block I control-pulse sequences. Transcribed from the reference
 * model in ext/agcplusplus/src/block1; unlike the Block II tables there
 * is no published memo here to diff them against, which is recorded as a
 * gap in docs/PROJECT_STATUS.md rather than glossed over.
 */
#include "subinst.h"

static const agc1_pulse_row ad0_rows[] = {
    {  1, 0x0, 0x0, { AGC1_P_RB, AGC1_P_WS } },  /* T1 xx */
    {  2, 0x0, 0x0, { AGC1_P_RA, AGC1_P_WY } },  /* T2 xx */
    {  3, 0x0, 0x0, { AGC1_P_WG } },  /* T3 xx */
    {  7, 0x0, 0x0, { AGC1_P_RG, AGC1_P_RSC, AGC1_P_WB, AGC1_P_WP } },  /* T7 xx */
    {  8, 0x0, 0x0, { AGC1_P_RB, AGC1_P_WX, AGC1_P_GP, AGC1_P_TP } },  /* T8 xx */
    {  9, 0x0, 0x0, { AGC1_P_RB, AGC1_P_WSC, AGC1_P_WG } },  /* T9 xx */
    { 11, 0x0, 0x0, { AGC1_P_RU, AGC1_P_WA, AGC1_P_WOVC, AGC1_P_ST2, AGC1_P_WOVI } },  /* T11 xx */
};

static const agc1_pulse_row ccs0_rows[] = {
    {  1, 0x0, 0x0, { AGC1_P_RB, AGC1_P_WS } },  /* T1 xx */
    {  2, 0x0, 0x0, { AGC1_P_RZ, AGC1_P_WY } },  /* T2 xx */
    {  3, 0x0, 0x0, { AGC1_P_WG } },  /* T3 xx */
    {  6, 0x0, 0x0, { AGC1_P_RG, AGC1_P_RSC, AGC1_P_WB, AGC1_P_TSGN, AGC1_P_WP } },  /* T6 xx */
    {  7, 0x2, 0x0, { AGC1_P_RC, AGC1_P_TMZ } },  /* T7 0x */
    {  7, 0x2, 0x2, { AGC1_P_RB, AGC1_P_TMZ } },  /* T7 1x */
    {  8, 0x3, 0x0, { AGC1_P_GP, AGC1_P_TP } },  /* T8 00 */
    {  8, 0x3, 0x1, { AGC1_P_R1, AGC1_P_WX, AGC1_P_GP, AGC1_P_TP } },  /* T8 01 */
    {  8, 0x3, 0x2, { AGC1_P_R2, AGC1_P_WX, AGC1_P_GP, AGC1_P_TP } },  /* T8 10 */
    {  8, 0x3, 0x3, { AGC1_P_R1, AGC1_P_R2, AGC1_P_WX, AGC1_P_GP, AGC1_P_TP } },  /* T8 11 */
    {  9, 0x0, 0x0, { AGC1_P_RB, AGC1_P_WSC, AGC1_P_WG } },  /* T9 xx */
    { 10, 0x1, 0x1, { AGC1_P_R1C, AGC1_P_WA } },  /* T10 x1 */
    { 10, 0x3, 0x0, { AGC1_P_RC, AGC1_P_WA } },  /* T10 00 */
    { 10, 0x3, 0x2, { AGC1_P_RB, AGC1_P_WA } },  /* T10 10 */
    { 11, 0x0, 0x0, { AGC1_P_RU, AGC1_P_ST1, AGC1_P_WZ } },  /* T11 xx */
};

static const agc1_pulse_row ccs1_rows[] = {
    {  1, 0x0, 0x0, { AGC1_P_RZ, AGC1_P_WY, AGC1_P_WS, AGC1_P_CI } },  /* T1 xx */
    {  3, 0x0, 0x0, { AGC1_P_WG } },  /* T3 xx */
    {  4, 0x0, 0x0, { AGC1_P_RU, AGC1_P_WZ } },  /* T4 xx */
    {  5, 0x0, 0x0, { AGC1_P_RA, AGC1_P_WY, AGC1_P_CI } },  /* T5 xx */
    {  7, 0x0, 0x0, { AGC1_P_RG, AGC1_P_RSC, AGC1_P_WB, AGC1_P_WP } },  /* T7 xx */
    {  8, 0x0, 0x0, { AGC1_P_RU, AGC1_P_WB, AGC1_P_GP, AGC1_P_TP } },  /* T8 xx */
    { 10, 0x0, 0x0, { AGC1_P_RC, AGC1_P_WA, AGC1_P_WOVI } },  /* T10 xx */
    { 11, 0x0, 0x0, { AGC1_P_RG, AGC1_P_RSC, AGC1_P_WB, AGC1_P_NISQ } },  /* T11 xx */
};

static const agc1_pulse_row cs0_rows[] = {
    {  1, 0x0, 0x0, { AGC1_P_RB, AGC1_P_WS } },  /* T1 xx */
    {  3, 0x0, 0x0, { AGC1_P_WG } },  /* T3 xx */
    {  7, 0x0, 0x0, { AGC1_P_RG, AGC1_P_RSC, AGC1_P_WB, AGC1_P_WP } },  /* T7 xx */
    {  8, 0x0, 0x0, { AGC1_P_GP, AGC1_P_TP } },  /* T8 xx */
    {  9, 0x0, 0x0, { AGC1_P_RB, AGC1_P_WSC, AGC1_P_WG } },  /* T9 xx */
    { 10, 0x0, 0x0, { AGC1_P_RC, AGC1_P_WA, AGC1_P_WOVI } },  /* T10 xx */
    { 11, 0x0, 0x0, { AGC1_P_ST2 } },  /* T11 xx */
};

static const agc1_pulse_row dv0_rows[] = {
    {  1, 0x0, 0x0, { AGC1_P_RB, AGC1_P_WS } },  /* T1 xx */
    {  2, 0x0, 0x0, { AGC1_P_RA, AGC1_P_WB, AGC1_P_TSGN } },  /* T2 xx */
    {  3, 0x0, 0x0, { AGC1_P_RSC, AGC1_P_WG } },  /* T3 xx */
    {  4, 0x2, 0x0, { AGC1_P_RC, AGC1_P_WA } },  /* T4 0x */
    {  5, 0x2, 0x0, { AGC1_P_R1, AGC1_P_WLP } },  /* T5 0x */
    {  5, 0x2, 0x2, { AGC1_P_R2, AGC1_P_WLP } },  /* T5 1x */
    {  6, 0x0, 0x0, { AGC1_P_RA, AGC1_P_WQ } },  /* T6 xx */
    {  7, 0x0, 0x0, { AGC1_P_RG, AGC1_P_WB, AGC1_P_TSGN, AGC1_P_WP } },  /* T7 xx */
    {  8, 0x0, 0x0, { AGC1_P_RB, AGC1_P_WA, AGC1_P_GP, AGC1_P_TP } },  /* T8 xx */
    {  9, 0x2, 0x0, { AGC1_P_RLP, AGC1_P_R2, AGC1_P_WB } },  /* T9 0x */
    { 10, 0x2, 0x0, { AGC1_P_RB, AGC1_P_WLP } },  /* T10 0x */
    { 10, 0x2, 0x2, { AGC1_P_RC, AGC1_P_WA } },  /* T10 1x */
    { 11, 0x0, 0x0, { AGC1_P_R1, AGC1_P_ST1, AGC1_P_WB } },  /* T11 xx */
};

static const agc1_pulse_row dv1_rows[] = {
    {  1, 0x0, 0x0, { AGC1_P_R22, AGC1_P_WS } },  /* T1 xx */
    {  2, 0x0, 0x0, { AGC1_P_RQ, AGC1_P_WG } },  /* T2 xx */
    {  3, 0x0, 0x0, { AGC1_P_RG, AGC1_P_RSB, AGC1_P_WQ, AGC1_P_WY } },  /* T3 xx */
    {  4, 0x0, 0x0, { AGC1_P_RA, AGC1_P_WX } },  /* T4 xx */
    {  5, 0x0, 0x0, { AGC1_P_RLP, AGC1_P_TSGN2 } },  /* T5 xx */
    {  7, 0x0, 0x0, { AGC1_P_RU, AGC1_P_TSGN } },  /* T7 xx */
    {  8, 0x2, 0x2, { AGC1_P_RU, AGC1_P_WQ } },  /* T8 1x */
    {  9, 0x2, 0x0, { AGC1_P_RB, AGC1_P_RSB, AGC1_P_WG } },  /* T9 0x */
    {  9, 0x2, 0x2, { AGC1_P_RB, AGC1_P_WG } },  /* T9 1x */
    { 10, 0x0, 0x0, { AGC1_P_RG, AGC1_P_WB, AGC1_P_TSGN } },  /* T10 xx */
    { 11, 0x2, 0x0, { AGC1_P_ST1 } },  /* T11 0x */
    { 11, 0x3, 0x2, { AGC1_P_RC, AGC1_P_WA, AGC1_P_ST2 } },  /* T11 10 */
    { 11, 0x3, 0x3, { AGC1_P_RB, AGC1_P_WA, AGC1_P_ST2 } },  /* T11 11 */
};

static const agc1_pulse_row minc_rows[] = {
    {  1, 0x0, 0x0, { AGC1_P_RSCT, AGC1_P_WS } },  /* T1 xx */
    {  3, 0x0, 0x0, { AGC1_P_WG } },  /* T3 xx */
    {  4, 0x0, 0x0, { AGC1_P_R1C, AGC1_P_WY } },  /* T4 xx */
    {  6, 0x0, 0x0, { AGC1_P_RG, AGC1_P_WX, AGC1_P_WP } },  /* T6 xx */
    {  7, 0x0, 0x0, { AGC1_P_TP } },  /* T7 xx */
    {  8, 0x0, 0x0, { AGC1_P_WP } },  /* T8 xx */
    {  9, 0x0, 0x0, { AGC1_P_RU, AGC1_P_CLG, AGC1_P_WP } },  /* T9 xx */
    { 10, 0x0, 0x0, { AGC1_P_RU, AGC1_P_WG, AGC1_P_WOVR } },  /* T10 xx */
};

static const agc1_pulse_row mp0_rows[] = {
    {  1, 0x0, 0x0, { AGC1_P_SETMPCTR, AGC1_P_RB, AGC1_P_WS } },  /* T1 xx */
    {  2, 0x0, 0x0, { AGC1_P_RA, AGC1_P_WB, AGC1_P_TSGN } },  /* T2 xx */
    {  3, 0x0, 0x0, { AGC1_P_RSC, AGC1_P_WG } },  /* T3 xx */
    {  4, 0x2, 0x0, { AGC1_P_RB, AGC1_P_WLP } },  /* T4 0x */
    {  4, 0x2, 0x2, { AGC1_P_RC, AGC1_P_WLP } },  /* T4 1x */
    {  5, 0x0, 0x0, { AGC1_P_RLP, AGC1_P_WA } },  /* T5 xx */
    {  7, 0x2, 0x0, { AGC1_P_RG, AGC1_P_WY, AGC1_P_WP } },  /* T7 0x */
    {  7, 0x2, 0x2, { AGC1_P_RG, AGC1_P_WB, AGC1_P_WP } },  /* T7 1x */
    {  8, 0x2, 0x0, { AGC1_P_GP, AGC1_P_TP } },  /* T8 0x */
    {  8, 0x2, 0x2, { AGC1_P_RC, AGC1_P_WY, AGC1_P_GP, AGC1_P_TP } },  /* T8 1x */
    {  9, 0x0, 0x0, { AGC1_P_RU, AGC1_P_WB, AGC1_P_TSGN2 } },  /* T9 xx */
    { 10, 0x1, 0x0, { AGC1_P_RA, AGC1_P_WLP, AGC1_P_TSGN } },  /* T10 x0 */
    { 10, 0x1, 0x1, { AGC1_P_RA, AGC1_P_RB14, AGC1_P_WLP, AGC1_P_TSGN } },  /* T10 x1 */
    { 11, 0x2, 0x2, { AGC1_P_RU, AGC1_P_ST1, AGC1_P_WALP } },  /* T11 1x */
    { 11, 0x3, 0x0, { AGC1_P_ST1, AGC1_P_WALP } },  /* T11 00 */
    { 11, 0x3, 0x1, { AGC1_P_R1, AGC1_P_R1C, AGC1_P_ST1, AGC1_P_WALP } },  /* T11 01 */
};

static const agc1_pulse_row mp1_rows[] = {
    {  1, 0x0, 0x0, { AGC1_P_RA, AGC1_P_WY } },  /* T1 xx */
    {  2, 0x0, 0x0, { AGC1_P_RLP, AGC1_P_WA, AGC1_P_TSGN } },  /* T2 xx */
    {  3, 0x2, 0x2, { AGC1_P_RB, AGC1_P_WX } },  /* T3 1x */
    {  4, 0x0, 0x0, { AGC1_P_RA, AGC1_P_WLP } },  /* T4 xx */
    {  5, 0x0, 0x0, { AGC1_P_RLP, AGC1_P_TSGN } },  /* T5 xx */
    {  6, 0x0, 0x0, { AGC1_P_RU, AGC1_P_WALP } },  /* T6 xx */
    {  7, 0x0, 0x0, { AGC1_P_RA, AGC1_P_WY } },  /* T7 xx */
    {  8, 0x2, 0x2, { AGC1_P_RB, AGC1_P_WX } },  /* T8 1x */
    {  9, 0x0, 0x0, { AGC1_P_RLP, AGC1_P_WA } },  /* T9 xx */
    { 10, 0x0, 0x0, { AGC1_P_RA, AGC1_P_WLP, AGC1_P_CTR } },  /* T10 xx */
    { 11, 0x0, 0x0, { AGC1_P_RU, AGC1_P_ST1, AGC1_P_WALP } },  /* T11 xx */
};

static const agc1_pulse_row mp3_rows[] = {
    {  1, 0x0, 0x0, { AGC1_P_RZ, AGC1_P_WY, AGC1_P_WS, AGC1_P_CI } },  /* T1 xx */
    {  2, 0x0, 0x0, { AGC1_P_RLP, AGC1_P_TSGN } },  /* T2 xx */
    {  3, 0x0, 0x0, { AGC1_P_WG } },  /* T3 xx */
    {  4, 0x0, 0x0, { AGC1_P_RU, AGC1_P_WZ } },  /* T4 xx */
    {  5, 0x0, 0x0, { AGC1_P_RA, AGC1_P_WY } },  /* T5 xx */
    {  6, 0x2, 0x2, { AGC1_P_RB, AGC1_P_WX } },  /* T6 1x */
    {  7, 0x0, 0x0, { AGC1_P_RG, AGC1_P_RSC, AGC1_P_WB, AGC1_P_WP } },  /* T7 xx */
    {  8, 0x0, 0x0, { AGC1_P_RLP, AGC1_P_WA, AGC1_P_GP, AGC1_P_TP } },  /* T8 xx */
    {  9, 0x0, 0x0, { AGC1_P_RB, AGC1_P_WSC, AGC1_P_WG } },  /* T9 xx */
    { 10, 0x0, 0x0, { AGC1_P_RA, AGC1_P_WLP } },  /* T10 xx */
    { 11, 0x0, 0x0, { AGC1_P_RU, AGC1_P_WALP, AGC1_P_NISQ } },  /* T11 xx */
};

static const agc1_pulse_row msk0_rows[] = {
    {  1, 0x0, 0x0, { AGC1_P_RB, AGC1_P_WS } },  /* T1 xx */
    {  2, 0x0, 0x0, { AGC1_P_RA, AGC1_P_WB } },  /* T2 xx */
    {  3, 0x0, 0x0, { AGC1_P_WG } },  /* T3 xx */
    {  4, 0x0, 0x0, { AGC1_P_RC, AGC1_P_WY } },  /* T4 xx */
    {  7, 0x0, 0x0, { AGC1_P_RG, AGC1_P_RSC, AGC1_P_WB, AGC1_P_WP } },  /* T7 xx */
    {  8, 0x0, 0x0, { AGC1_P_RU, AGC1_P_RC, AGC1_P_WA, AGC1_P_GP, AGC1_P_TP } },  /* T8 xx */
    { 10, 0x0, 0x0, { AGC1_P_RA, AGC1_P_WB } },  /* T10 xx */
    { 11, 0x0, 0x0, { AGC1_P_RC, AGC1_P_WA, AGC1_P_ST2, AGC1_P_WOVI } },  /* T11 xx */
};

static const agc1_pulse_row ndx0_rows[] = {
    {  1, 0x0, 0x0, { AGC1_P_RB, AGC1_P_WS } },  /* T1 xx */
    {  3, 0x0, 0x0, { AGC1_P_WG } },  /* T3 xx */
    {  4, 0x0, 0x0, { AGC1_P_RA, AGC1_P_WOVI } },  /* T4 xx */
    {  7, 0x0, 0x0, { AGC1_P_RG, AGC1_P_RSC, AGC1_P_WB, AGC1_P_WP } },  /* T7 xx */
    {  8, 0x0, 0x0, { AGC1_P_GP, AGC1_P_TP } },  /* T8 xx */
    {  9, 0x0, 0x0, { AGC1_P_RB, AGC1_P_WSC, AGC1_P_WG } },  /* T9 xx */
    { 10, 0x0, 0x0, { AGC1_P_TRSM } },  /* T10 xx */
    { 11, 0x0, 0x0, { AGC1_P_ST1 } },  /* T11 xx */
};

static const agc1_pulse_row ndx1_rows[] = {
    {  1, 0x0, 0x0, { AGC1_P_RZ, AGC1_P_WY, AGC1_P_WS, AGC1_P_CI } },  /* T1 xx */
    {  3, 0x0, 0x0, { AGC1_P_WG } },  /* T3 xx */
    {  4, 0x0, 0x0, { AGC1_P_RU, AGC1_P_WZ } },  /* T4 xx */
    {  6, 0x0, 0x0, { AGC1_P_RB, AGC1_P_WY } },  /* T6 xx */
    {  7, 0x0, 0x0, { AGC1_P_RG, AGC1_P_RSC, AGC1_P_WB, AGC1_P_WP } },  /* T7 xx */
    {  8, 0x0, 0x0, { AGC1_P_RB, AGC1_P_WX, AGC1_P_GP, AGC1_P_TP } },  /* T8 xx */
    {  9, 0x0, 0x0, { AGC1_P_RB, AGC1_P_WSC, AGC1_P_WG } },  /* T9 xx */
    { 11, 0x0, 0x0, { AGC1_P_RU, AGC1_P_WB, AGC1_P_WOVI, AGC1_P_NISQ } },  /* T11 xx */
};

static const agc1_pulse_row pinc_rows[] = {
    {  1, 0x0, 0x0, { AGC1_P_RSCT, AGC1_P_WS } },  /* T1 xx */
    {  3, 0x0, 0x0, { AGC1_P_WG } },  /* T3 xx */
    {  4, 0x0, 0x0, { AGC1_P_R1, AGC1_P_WY } },  /* T4 xx */
    {  6, 0x0, 0x0, { AGC1_P_RG, AGC1_P_WX, AGC1_P_WP } },  /* T6 xx */
    {  7, 0x0, 0x0, { AGC1_P_TP } },  /* T7 xx */
    {  8, 0x0, 0x0, { AGC1_P_WP } },  /* T8 xx */
    {  9, 0x0, 0x0, { AGC1_P_RU, AGC1_P_CLG, AGC1_P_WP } },  /* T9 xx */
    { 10, 0x0, 0x0, { AGC1_P_RU, AGC1_P_WG, AGC1_P_WOVR } },  /* T10 xx */
};

static const agc1_pulse_row rsm_rows[] = {
    {  1, 0x0, 0x0, { AGC1_P_R24, AGC1_P_WS } },  /* T1 xx */
    {  3, 0x0, 0x0, { AGC1_P_WG } },  /* T3 xx */
    {  7, 0x0, 0x0, { AGC1_P_RG, AGC1_P_WZ } },  /* T7 xx */
    { 11, 0x0, 0x0, { AGC1_P_NISQ, AGC1_P_CLRIIP } },  /* T11 xx */
};

static const agc1_pulse_row rupt1_rows[] = {
    {  1, 0x0, 0x0, { AGC1_P_R24, AGC1_P_WY, AGC1_P_WS, AGC1_P_CI } },  /* T1 xx */
    {  3, 0x0, 0x0, { AGC1_P_WG } },  /* T3 xx */
    {  9, 0x0, 0x0, { AGC1_P_RZ, AGC1_P_WG } },  /* T9 xx */
    { 10, 0x0, 0x0, { AGC1_P_RU, AGC1_P_WZ } },  /* T10 xx */
    { 11, 0x0, 0x0, { AGC1_P_ST1, AGC1_P_ST2 } },  /* T11 xx */
};

static const agc1_pulse_row rupt3_rows[] = {
    {  1, 0x0, 0x0, { AGC1_P_RZ, AGC1_P_WS } },  /* T1 xx */
    {  2, 0x0, 0x0, { AGC1_P_RRPA, AGC1_P_WZ } },  /* T2 xx */
    {  3, 0x0, 0x0, { AGC1_P_RZ, AGC1_P_KRPT, AGC1_P_WG } },  /* T3 xx */
    {  9, 0x0, 0x0, { AGC1_P_RB, AGC1_P_WSC, AGC1_P_WG } },  /* T9 xx */
    { 11, 0x0, 0x0, { AGC1_P_ST2 } },  /* T11 xx */
};

static const agc1_pulse_row std2_rows[] = {
    {  1, 0x0, 0x0, { AGC1_P_RZ, AGC1_P_WY, AGC1_P_WS, AGC1_P_CI } },  /* T1 xx */
    {  3, 0x0, 0x0, { AGC1_P_WG } },  /* T3 xx */
    {  4, 0x0, 0x0, { AGC1_P_RU, AGC1_P_WZ } },  /* T4 xx */
    {  7, 0x0, 0x0, { AGC1_P_RG, AGC1_P_RSC, AGC1_P_WB, AGC1_P_WP } },  /* T7 xx */
    {  8, 0x0, 0x0, { AGC1_P_GP, AGC1_P_TP } },  /* T8 xx */
    {  9, 0x0, 0x0, { AGC1_P_RB, AGC1_P_WSC, AGC1_P_WG } },  /* T9 xx */
    { 11, 0x0, 0x0, { AGC1_P_NISQ } },  /* T11 xx */
};

static const agc1_pulse_row su0_rows[] = {
    {  1, 0x0, 0x0, { AGC1_P_RB, AGC1_P_WS } },  /* T1 xx */
    {  2, 0x0, 0x0, { AGC1_P_RA, AGC1_P_WY } },  /* T2 xx */
    {  3, 0x0, 0x0, { AGC1_P_WG } },  /* T3 xx */
    {  7, 0x0, 0x0, { AGC1_P_RG, AGC1_P_RSC, AGC1_P_WB, AGC1_P_WP } },  /* T7 xx */
    {  8, 0x0, 0x0, { AGC1_P_RC, AGC1_P_WX, AGC1_P_GP, AGC1_P_TP } },  /* T8 xx */
    {  9, 0x0, 0x0, { AGC1_P_RB, AGC1_P_WSC, AGC1_P_WG } },  /* T9 xx */
    { 11, 0x0, 0x0, { AGC1_P_RU, AGC1_P_WA, AGC1_P_WOVC, AGC1_P_ST2, AGC1_P_WOVI } },  /* T11 xx */
};

static const agc1_pulse_row tc0_rows[] = {
    {  1, 0x0, 0x0, { AGC1_P_RB, AGC1_P_WY, AGC1_P_WS, AGC1_P_CI } },  /* T1 xx */
    {  3, 0x0, 0x0, { AGC1_P_WG } },  /* T3 xx */
    {  4, 0x0, 0x0, { AGC1_P_RA, AGC1_P_WOVI } },  /* T4 xx */
    {  7, 0x0, 0x0, { AGC1_P_RG, AGC1_P_RSC, AGC1_P_WB, AGC1_P_WP } },  /* T7 xx */
    {  8, 0x0, 0x0, { AGC1_P_RZ, AGC1_P_WQ, AGC1_P_GP, AGC1_P_TP } },  /* T8 xx */
    {  9, 0x0, 0x0, { AGC1_P_RB, AGC1_P_WSC, AGC1_P_WG } },  /* T9 xx */
    { 10, 0x0, 0x0, { AGC1_P_RU, AGC1_P_WZ } },  /* T10 xx */
    { 11, 0x0, 0x0, { AGC1_P_NISQ } },  /* T11 xx */
};

static const agc1_pulse_row ts0_rows[] = {
    {  1, 0x0, 0x0, { AGC1_P_RB, AGC1_P_WS } },  /* T1 xx */
    {  2, 0x0, 0x0, { AGC1_P_RA, AGC1_P_WB, AGC1_P_TOV, AGC1_P_WP } },  /* T2 xx */
    {  3, 0x0, 0x0, { AGC1_P_WG } },  /* T3 xx */
    {  4, 0x3, 0x1, { AGC1_P_RZ, AGC1_P_WY, AGC1_P_CI } },  /* T4 01 */
    {  4, 0x3, 0x2, { AGC1_P_RZ, AGC1_P_WY, AGC1_P_CI } },  /* T4 10 */
    {  5, 0x3, 0x1, { AGC1_P_R1, AGC1_P_WA } },  /* T5 01 */
    {  5, 0x3, 0x2, { AGC1_P_R1C, AGC1_P_WA } },  /* T5 10 */
    {  7, 0x3, 0x1, { AGC1_P_RU, AGC1_P_WZ } },  /* T7 01 */
    {  7, 0x3, 0x2, { AGC1_P_RU, AGC1_P_WZ } },  /* T7 10 */
    {  8, 0x0, 0x0, { AGC1_P_GP } },  /* T8 xx */
    {  9, 0x0, 0x0, { AGC1_P_RB, AGC1_P_WSC, AGC1_P_WG } },  /* T9 xx */
    { 10, 0x0, 0x0, { AGC1_P_RA, AGC1_P_WOVI } },  /* T10 xx */
    { 11, 0x0, 0x0, { AGC1_P_ST2 } },  /* T11 xx */
};

static const agc1_pulse_row xch0_rows[] = {
    {  1, 0x0, 0x0, { AGC1_P_RB, AGC1_P_WS } },  /* T1 xx */
    {  2, 0x0, 0x0, { AGC1_P_RA, AGC1_P_WP } },  /* T2 xx */
    {  3, 0x0, 0x0, { AGC1_P_WG } },  /* T3 xx */
    {  4, 0x0, 0x0, { AGC1_P_WP2 } },  /* T4 xx */
    {  7, 0x0, 0x0, { AGC1_P_RG, AGC1_P_RSC, AGC1_P_WB, AGC1_P_WP } },  /* T7 xx */
    {  8, 0x0, 0x0, { AGC1_P_GP, AGC1_P_TP } },  /* T8 xx */
    {  9, 0x0, 0x0, { AGC1_P_RA, AGC1_P_RP2, AGC1_P_WSC, AGC1_P_WG } },  /* T9 xx */
    { 10, 0x0, 0x0, { AGC1_P_RB, AGC1_P_WA, AGC1_P_WOVI } },  /* T10 xx */
    { 11, 0x0, 0x0, { AGC1_P_ST2 } },  /* T11 xx */
};

const agc1_subinst agc1_subinst_table[] = {
    { "STD2", 2, false, 000, 0000, std2_rows, (uint8_t)(sizeof std2_rows / sizeof *std2_rows) },
    { "STD2", 2, true, 000, 0000, std2_rows, (uint8_t)(sizeof std2_rows / sizeof *std2_rows) },
    { "TC0", 0, false, 017, 0000, tc0_rows, (uint8_t)(sizeof tc0_rows / sizeof *tc0_rows) },
    { "XCH0", 0, false, 017, 0003, xch0_rows, (uint8_t)(sizeof xch0_rows / sizeof *xch0_rows) },
    { "CS0", 0, false, 017, 0014, cs0_rows, (uint8_t)(sizeof cs0_rows / sizeof *cs0_rows) },
    { "TS0", 0, false, 017, 0015, ts0_rows, (uint8_t)(sizeof ts0_rows / sizeof *ts0_rows) },
    { "MSK0", 0, false, 017, 0017, msk0_rows, (uint8_t)(sizeof msk0_rows / sizeof *msk0_rows) },
    { "AD0", 0, false, 017, 0016, ad0_rows, (uint8_t)(sizeof ad0_rows / sizeof *ad0_rows) },
    { "NDX0", 0, false, 017, 0002, ndx0_rows, (uint8_t)(sizeof ndx0_rows / sizeof *ndx0_rows) },
    { "NDX1", 1, false, 017, 0002, ndx1_rows, (uint8_t)(sizeof ndx1_rows / sizeof *ndx1_rows) },
    { "CCS0", 0, false, 017, 0001, ccs0_rows, (uint8_t)(sizeof ccs0_rows / sizeof *ccs0_rows) },
    { "CCS1", 1, false, 017, 0001, ccs1_rows, (uint8_t)(sizeof ccs1_rows / sizeof *ccs1_rows) },
    { "SU0", 0, true, 017, 0013, su0_rows, (uint8_t)(sizeof su0_rows / sizeof *su0_rows) },
    { "MP0", 0, true, 017, 0011, mp0_rows, (uint8_t)(sizeof mp0_rows / sizeof *mp0_rows) },
    { "MP1", 1, true, 017, 0011, mp1_rows, (uint8_t)(sizeof mp1_rows / sizeof *mp1_rows) },
    { "MP3", 3, true, 017, 0011, mp3_rows, (uint8_t)(sizeof mp3_rows / sizeof *mp3_rows) },
    { "DV0", 0, true, 017, 0012, dv0_rows, (uint8_t)(sizeof dv0_rows / sizeof *dv0_rows) },
    { "DV1", 1, true, 017, 0012, dv1_rows, (uint8_t)(sizeof dv1_rows / sizeof *dv1_rows) },
    { "RUPT1", 1, false, 017, 0003, rupt1_rows, (uint8_t)(sizeof rupt1_rows / sizeof *rupt1_rows) },
    { "RUPT3", 3, false, 017, 0003, rupt3_rows, (uint8_t)(sizeof rupt3_rows / sizeof *rupt3_rows) },
    { "RSM", 3, false, 017, 0002, rsm_rows, (uint8_t)(sizeof rsm_rows / sizeof *rsm_rows) },
};
const size_t agc1_subinst_count = sizeof agc1_subinst_table / sizeof *agc1_subinst_table;

/* Involuntary sequences, injected by priority control. */
const agc1_subinst agc1_subinst_minc = { "MINC", 0, false, 0, 0, minc_rows, (uint8_t)(sizeof minc_rows / sizeof *minc_rows) };
const agc1_subinst agc1_subinst_pinc = { "PINC", 0, false, 0, 0, pinc_rows, (uint8_t)(sizeof pinc_rows / sizeof *pinc_rows) };
