/* Block I control pulses and subinstruction sequences.
 *
 * Block I is the machine that flew unmanned on Apollo 4 and 6, and it is a
 * different computer from the Block II this project models everywhere else —
 * not an earlier revision of it. Eleven order codes rather than thirty-odd. LP
 * where Block II has L. Four input and five output registers instead of
 * sixty-four channels. One bank register, no superbanks, and a memory map that
 * puts erasable at 0-1777 and fixed-fixed at 2000-5777.
 *
 * What it shares is the shape of the sequence generator: one subinstruction per
 * memory cycle, twelve timing pulses, and a table saying which control pulses
 * fire at which pulse under which branch condition. So the tables here are
 * generated by the same machinery (`tools/gen_block1_tables.py`, which reuses
 * the Block II parser), and the executor is the same three-phase tick.
 *
 * One thing is *not* the same, and it is the reason this core states its
 * provenance loudly: there is no Block I equivalent of AGC4 Memo #9 in
 * `docs/references/`. The Block II tables are diffed against a published memo
 * and against gate netlists; these are transcribed from `ext/agcplusplus`
 * alone. That is a real difference in how much the two are worth, and it is
 * recorded in `docs/PROJECT_STATUS.md` rather than left for someone to assume.
 */
#ifndef AGC1_SUBINST_H
#define AGC1_SUBINST_H

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

/* The memo's own bound for Block II is five pulses in a timing pulse; Block I
 * stays inside six as well, and the generator asserts it rather than assuming. */
#define AGC1_MAX_PULSES_PER_TIMEPULSE 6

enum agc1_pulse {
    AGC1_P_NONE = 0,

    /* Reads onto the write lines. */
    AGC1_P_RA, AGC1_P_RB, AGC1_P_RB14, AGC1_P_RC, AGC1_P_RG, AGC1_P_RLP,
    AGC1_P_RP2, AGC1_P_RQ, AGC1_P_RSB, AGC1_P_RSC, AGC1_P_RSCT, AGC1_P_RU,
    AGC1_P_RZ, AGC1_P_R1, AGC1_P_R1C, AGC1_P_R2, AGC1_P_R22, AGC1_P_R24,
    AGC1_P_RRPA,

    /* Writes off them. */
    AGC1_P_WA, AGC1_P_WALP, AGC1_P_WB, AGC1_P_WG, AGC1_P_WLP, AGC1_P_WP,
    AGC1_P_WP2, AGC1_P_WQ, AGC1_P_WS, AGC1_P_WSC, AGC1_P_WX, AGC1_P_WY,
    AGC1_P_WZ,

    /* The adder, the parity/overflow logic and the sequence generator. */
    AGC1_P_CI, AGC1_P_CLG, AGC1_P_CTR, AGC1_P_GP, AGC1_P_TP,
    AGC1_P_WOVC, AGC1_P_WOVI, AGC1_P_WOVR,
    AGC1_P_TMZ, AGC1_P_TOV, AGC1_P_TSGN, AGC1_P_TSGN2, AGC1_P_TRSM,
    AGC1_P_ST1, AGC1_P_ST2, AGC1_P_NISQ, AGC1_P_KRPT,

    /* Signals with no mnemonic of their own, given synthetic pulses so they
     * cannot be silently dropped — the lesson of FINDINGS #16. SETMPCTR is
     * MP0 T1 loading the multiply repeat counter; CLRIIP is RESUME dropping the
     * interrupt-in-progress line. */
    AGC1_P_SETMPCTR, AGC1_P_CLRIIP,

    AGC1_P_COUNT
};

/* One row: "at timing pulse `tp`, if (br & br_mask) == br_value, assert these". */
typedef struct agc1_pulse_row {
    uint8_t tp;
    uint8_t br_mask;
    uint8_t br_value;
    uint8_t pulse[AGC1_MAX_PULSES_PER_TIMEPULSE];
} agc1_pulse_row;

typedef struct agc1_subinst {
    const char *name;
    uint8_t stage;
    bool extend;
    uint8_t sq_mask;
    uint8_t sq_value;
    const agc1_pulse_row *rows;
    uint8_t row_count;
} agc1_subinst;

extern const agc1_subinst agc1_subinst_table[];
extern const size_t agc1_subinst_count;

/* Injected by priority control rather than decoded. */
extern const agc1_subinst agc1_subinst_pinc;
extern const agc1_subinst agc1_subinst_minc;

const char *agc1_pulse_name(enum agc1_pulse p);

#endif /* AGC1_SUBINST_H */
