#!/usr/bin/env python3
"""Generate src/core_block1/subinst_tables.c — the Block I pulse sequences.

Block I is a different machine, not a variant: eleven order codes instead of
thirty-odd, no EXTEND on its own (the extend bit is part of the order code
space), LP where Block II has L, four input and five output registers instead
of sixty-four channels, one bank register and no superbanks.

What it shares with Block II is the *shape* of the sequence generator — a
subinstruction per memory cycle, twelve timing pulses, a table of control pulses
per (timing pulse, branch condition) — so this reuses the Block II generator's
parser wholesale and only differs in where the dispatch table lives and how its
fields are ordered.

There is no Block I equivalent of AGC4 Memo #9 in `docs/references/`, so unlike
the Block II tables these are checked against the reference model alone. That is
recorded as the gap it is, in `docs/PROJECT_STATUS.md`.

Usage:  python3 tools/gen_block1_tables.py [--check]
"""

from __future__ import annotations

import argparse
import importlib.util
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "ext/agcplusplus/src/block1"
OUT = ROOT / "src/core_block1/subinst_tables.c"

# Reuse the Block II generator's parser rather than writing a second one: the
# subinstruction bodies are the same C++ shape, and a second parser would be a
# second thing to get subtly wrong.
_spec = importlib.util.spec_from_file_location(
    "gen_block2", ROOT / "tools" / "gen_subinst_tables.py")
_b2 = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(_b2)

AGC_MAX_PULSES = 6

# Block I pokes one piece of state that has no control-pulse mnemonic: MP0 T1
# loads the multiply repeat counter with 5, which CTR then walks down to decide
# when the MP1 loop has run its six times. The Block II generator hard-errors on
# any unmapped bare assignment rather than dropping it — the lesson of FINDINGS
# #16 — so it is given a synthetic pulse here and implemented in pulses.c, the
# same treatment 1xP10 and 8xP5 get on the other machine.
_b2.BARE_ASSIGNMENTS[("multiply_counter", "5")] = "setmpctr"


def parse_subinstructions() -> dict:
    text = (SRC / "subinstructions.cpp").read_text()
    result: dict = {}
    for m in re.finditer(r"^\s*void\s+([a-z0-9_]+)\s*\(\s*Cpu&\s*cpu\s*\)\s*\{", text, re.M):
        name = m.group(1)
        body, _ = _b2.extract_block(text, m.start())
        tp_switch = re.search(r"switch\s*\(\s*cpu\.timepulse\s*\)", body)
        if not tp_switch:
            continue
        tp_block, _ = _b2.extract_block(body, tp_switch.end())
        rows: dict = {}
        for labels, stmts in _b2.split_top_level_cases(tp_block):
            for label in labels:
                tp = int(label)
                by_br = {br: _b2.eval_body(stmts, br) for br in range(4)}
                rows[tp] = _b2.collapse(by_br)
        result[name] = rows
    return result


def parse_dispatch() -> list[tuple[str, int, bool, int, int]]:
    """Block I's table is {name, stage, extended, mask, order_code, fn}."""
    text = (SRC / "subinstructions.hpp").read_text()
    block = text[text.index("subinstruction_data[]"):]
    block = block[: block.index("};")]
    out = []
    for m in re.finditer(
        r'\{\s*"([A-Z0-9]+)",\s*(\d+),\s*(true|false),\s*(0[0-7]*),\s*(0[0-7]*)', block
    ):
        name, stage, ext, mask, op = m.groups()
        out.append((name, int(stage), ext == "true", int(mask, 8), int(op, 8)))
    return out


def pulse_enum(name: str) -> str:
    return "AGC1_P_" + name.upper()


def emit(parsed, dispatch) -> str:
    widest = max(len(ps) for rows in parsed.values()
                 for variants in rows.values() for _, _, ps in variants)
    if widest > AGC_MAX_PULSES:
        raise SystemExit(f"a Block I sequence asserts {widest} pulses in one "
                         f"timing pulse; raise AGC1_MAX_PULSES_PER_TIMEPULSE")

    lines = [
        "/* GENERATED by tools/gen_block1_tables.py — do not edit by hand.",
        " *",
        " * The Block I control-pulse sequences. Transcribed from the reference",
        " * model in ext/agcplusplus/src/block1; unlike the Block II tables there",
        " * is no published memo here to diff them against, which is recorded as a",
        " * gap in docs/PROJECT_STATUS.md rather than glossed over.",
        " */",
        '#include "subinst.h"',
        "",
    ]

    for name, rows in sorted(parsed.items()):
        lines.append(f"static const agc1_pulse_row {name}_rows[] = {{")
        for tp in sorted(rows):
            for mask, value, ps in rows[tp]:
                cond = "".join("x" if not (mask & bit) else ("1" if value & bit else "0")
                               for bit in (0b10, 0b01))
                pl = ", ".join(pulse_enum(p) for p in ps)
                lines.append(f"    {{ {tp:2d}, 0x{mask:x}, 0x{value:x}, {{ {pl} }} }},"
                             f"  /* T{tp} {cond} */")
        lines.append("};")
        lines.append("")

    lines.append("const agc1_subinst agc1_subinst_table[] = {")
    seen = set()
    for name, stage, ext, mask, op in dispatch:
        fn = name.lower()
        if fn not in parsed:
            continue
        lines.append(
            f'    {{ "{name}", {stage}, {"true" if ext else "false"}, '
            f"0{mask:02o}, 0{op:03o}, {fn}_rows, "
            f"(uint8_t)(sizeof {fn}_rows / sizeof *{fn}_rows) }},")
        seen.add(fn)
    lines.append("};")
    lines.append("const size_t agc1_subinst_count = "
                 "sizeof agc1_subinst_table / sizeof *agc1_subinst_table;")
    lines.append("")
    lines.append("/* Involuntary sequences, injected by priority control. */")
    for fn in sorted(set(parsed) - seen):
        lines.append(f"const agc1_subinst agc1_subinst_{fn} = "
                     f'{{ "{fn.upper()}", 0, false, 0, 0, {fn}_rows, '
                     f"(uint8_t)(sizeof {fn}_rows / sizeof *{fn}_rows) }};")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()

    if not (SRC / "subinstructions.cpp").exists():
        print("ext/agcplusplus is missing. Run: "
              "git submodule update --init ext/agcplusplus", file=sys.stderr)
        return 1

    parsed = parse_subinstructions()
    dispatch = parse_dispatch()
    text = emit(parsed, dispatch)

    pulses = sorted({p for rows in parsed.values() for variants in rows.values()
                     for _, _, ps in variants for p in ps})
    print(f"{len(parsed)} sequences, {len(pulses)} distinct control pulses",
          file=sys.stderr)

    if args.check:
        if not OUT.exists() or OUT.read_text() != text:
            print(f"{OUT} is stale; re-run without --check", file=sys.stderr)
            return 1
        return 0

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(text)
    print(f"wrote {OUT} ({len(parsed)} subinstructions)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
