#!/usr/bin/env python3
"""Hash the machine state after a long run of each core rope.

The probe goldens pin small, deliberate measurements. This pins something
different and complementary: the *whole* of erasable memory plus the register
file after 200 000 Memory Cycle Times — 2.34 emulated seconds — of real flight
software. Nobody reads these numbers. Their job is to change when something
changes.

This is the identity harness the guide asks for before any optimization work
(§1, §12): "1.9x faster and bit-identical" is a claim you can only make if you
have something that would have noticed. It is also the widest net in the
project. The probes check what we thought to check; a rope hash notices any
divergence anywhere in 2048 words of erasable memory, in software far more
intricate than anything we would write by hand.

The hashes are emulated machine state, not measurements of this computer, so
they are identical on every host and both build types. A platform where one
differs has a real bug.

Ropes are not committed — they are rebuilt from the Virtual AGC submodule by
tools/build_ropes.sh — so this skips cleanly when roms/ is empty, and CI stays
green without them.

Usage:
    tools/hash_ropes.py --exe build/.../agc_headless
    tools/hash_ropes.py --exe ... --bless      # rewrite the goldens
"""
from __future__ import annotations

import argparse
import hashlib
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
ROMS = ROOT / "roms"
GOLDEN = ROOT / "tests/goldens/rope-hashes.txt"
MCT = 200000
ERASABLE_WORDS = 2048


def rope_images() -> list[Path]:
    return sorted(p for d in sorted(ROMS.iterdir()) if d.is_dir()
                  for p in sorted(d.glob("*.bin")))


def run(exe: str, rope: Path, mct: int) -> tuple[str, bool]:
    """Return (hash, alarmed) for one rope."""
    out = subprocess.run(
        [exe, "--rope", str(rope), "--mct", str(mct),
         "--dump-state", "--dump-mem", f"0:{ERASABLE_WORDS}", "--dump-counters",
         "--dump-dsky"],
        capture_output=True, text=True)
    if out.returncode != 0:
        raise SystemExit(f"{rope.name}: emulator exited {out.returncode}\n{out.stderr}")

    # stderr carries the "loaded N words" notice, which is not machine state.
    body = out.stdout
    alarmed = "alarm=1" in body
    return hashlib.sha256(body.encode()).hexdigest(), alarmed


def load_golden() -> dict[str, str]:
    if not GOLDEN.exists():
        return {}
    out = {}
    for line in GOLDEN.read_text().splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        name, mct, digest = line.split()
        out[f"{name}@{mct}"] = digest
    return out


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--exe", required=True)
    ap.add_argument("--mct", type=int, default=MCT)
    ap.add_argument("--bless", action="store_true")
    args = ap.parse_args()

    if not ROMS.is_dir() or not rope_images():
        print("roms/ is empty; skipping the rope hashes. "
              "Run ./tools/build_ropes.sh to populate it.")
        return 0

    golden = load_golden()
    lines = [
        "# Machine state after a long run of each core rope: the whole of",
        "# erasable memory, the register file and the counter cells, hashed.",
        "# Generated by tools/hash_ropes.py --bless. These are emulated machine",
        "# state, so they are identical on every host and both build types.",
        "# <rope> <mct> <sha256 of the headless dump>",
    ]
    failures: list[str] = []

    for rope in rope_images():
        name = rope.stem
        digest, alarmed = run(args.exe, rope, args.mct)
        key = f"{name}@{args.mct}"
        note = "  (latches a hardware alarm)" if alarmed else ""
        lines.append(f"{name} {args.mct} {digest}")

        if args.bless:
            print(f"  {name:<14} {digest[:16]}...{note}")
        elif key not in golden:
            failures.append(f"{name}: no golden for {args.mct} MCT — run with --bless")
        elif golden[key] != digest:
            failures.append(
                f"{name}: state after {args.mct} MCT changed\n"
                f"    golden {golden[key]}\n"
                f"    ours   {digest}")
        else:
            print(f"  {name:<14} unchanged{note}")

    if args.bless:
        GOLDEN.write_text("\n".join(lines) + "\n")
        print(f"blessed {GOLDEN.relative_to(ROOT)}")
        return 0

    if failures:
        print("\n".join(failures), file=sys.stderr)
        print("\nA changed hash is not automatically a regression — but it is "
              "always a behaviour change, and the commit that causes one has to "
              "say why.", file=sys.stderr)
        return 1

    print(f"{len(rope_images())} rope(s) unchanged after {args.mct} MCT")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
